#+LATEX_HEADER_EXTRA: \usepackage{indentfirst}
#+LATEX_HEADER_EXTRA: \usepackage{amsmath}

* What is Calculus About ?

* Solution 1

  $s(t) = t^2 - 3$

  * t is time in seconds
  * s(t) is position in meteres

** Solution (a)

   $\dfrac{s(5) - s(2)}{5-2}$

   $\dfrac{5^2 - 3 - (2^2 - 3)}{3}$

** Solution (b)

   $\dfrac{f(2+x) - f(2)}{2 + x - 2}$

   $\dfrac{(2+x)^2 - 3 - (2^2 - 3)}{x}$

   $x + 4$

** Solution (c)

   Graph solution. Skipped as of now.

** Solution (d)

   From result in (c), we know that $f(x) = x + 4$

   We need to find, $\lim_{x \to 0}$ f(x)$

   and the above limit value is $4$.

* Solution 2

  $s(t) = sin(\pi)$

  * length = feet
  * time t = minutes

** Solution (a)

   Average velocity $= \dfrac{s(3) - s(1)}{3 - 1}$

   $= \dfrac{sin(3\pi) - sin(\pi)}{2}$

   $= \dfrac{sin(\pi) - sin(\pi)}{2} = 0$

** Solution (b)

   $f(x) = \dfrac{s(1 + x) - s(1)}{1 + x - 1}$

   $= \dfrac{sin(\pi(1 + x)) - sin(\pi)}{x}$

** Solution (c)

   When $x$ gets close to 0, $sin(\pi(1 + x))$ becomes $sin \pi$. This
   makes the numerator to zero. So, the velocity of the object at $t =
   1$ is zero.

* Solution 3

$\lim_{x \to 3} \dfrac{3 - x}{x^2 - x - 6}$

$= \lim_{x \to 3} \dfrac{3 - x}{x(x-1) - 6}$

$= \lim_{x \to 3} \dfrac{3 - x}{(x + 2)(x - 3)}$

$= \lim_{x \to 3} \dfrac{1}{(x + 2)(-1)}$

$= \dfrac{1}{5x - 1} = -1\dfrac{1}{5}$

* Solution 4

$\lim_{x \to 1} \dfrac{(x + 2)^2 - 9}{(x + 1)^2 - 4}$

$= \lim_{x \to 1} \dfrac{(x + 2)^2 - 3^2}{(x + 1)^2 - 2^2}$

$= \lim_{x \to 1} \dfrac{(x + 2 - 3)(x + 2 + 3)}{(x + 1 - 2)(x + 1 + 2)}$

$= \lim_{x \to 1} \dfrac{(x - 1)(x + 5)}{(x - 1)(x + 3)}$

$= \lim_{x \to 1} \dfrac{x + 5}{x + 3}$

$= \dfrac{6}{4} = \dfrac{3}{2}$

* Solution 5

$\lim_{x \to 0} \dfrac{\sqrt{x + 1} - 1}{x}$

$\lim_{x \to 0} \dfrac{(\sqrt{x + 1} - 1)(\sqrt{x + 1} + 1)}{x(\sqrt{x + 1} + 1)}$

$\lim_{x \to 0} \dfrac{x + 1 - 1}{x(\sqrt{x + 1} + 1)}$

$\lim_{x \to 0} \dfrac{1}{\sqrt{x + 1} + 1}$

$\dfrac{1}{\sqrt{1} + 1} = \dfrac{1}{2}$

* Solution 6

$\lim_{x \to 0} \dfrac{\sqrt[3]{x + 1} - 1}{x}$

$\lim_{x \to 0} \dfrac{(\sqrt[3]{x + 1} - 1)((\sqrt[3]{x+1} + 1)^2 + (\sqrt[3]{x + 1} + 1) + 1{x})}{x((\sqrt[3]{x+1} + 1)^2 + (\sqrt[3]{x + 1} + 1) + 1{x})}$

We know that a^3 - b^3 = (a - b)(a^2 + ab + b^2)

$\dfrac{(x + 1) - 1}{x((\sqrt[3]{x+1} + 1)^2 + (\sqrt[3]{x + 1} + 1) + 1{x})}$

Substituting $x$ with 0, we get,

\dfrac{1}{1 + 1 + 1} = \dfrac{1}{3}

* Solution 7

$\lim_{x \to 64} \dfrac{\sqrt[3]{x} - 4}{\sqrt{x} - 8}$

$\lim_{x \to 64} \dfrac{(\sqrt[3]{x} - 4)((\sqrt[3]{x})^2 + 4^2 + 4.\sqrt{3}{x})}{(\sqrt{x} - 8)((\sqrt[3]{x})^2 + 4^2 + 4.\sqrt{3}{x})}$

We know that a^3 - b^3 = (a - b)(a^2 + ab + b^2)

Simplifying it we get, $\dfrac{\sqrt{x} + 8}{x^(2/3) + 16 + \sqrt[3]{x}.4}$

Substituting $x$ with 64, we get, $\dfrac{16}{4^2 + 16 + 16}$ which gets simplified to $\dfrac{1}{3}$

* Solution 8

$\lim_{x \to 0} \dfrac{1}{x} + \dfrac{1}{x^2 - x}$

$\lim_{x \to 0} \dfrac{1}{x}(1 + \dfrac{1}{x - 1})$

$\lim_{x \to 0} \dfrac{1}{x}(\dfrac{x}{x - 1})$

$\lim_{x \to 0} \dfrac{1}{x - 1}$

Substituting $x$ with 0, we get $-1$

* Solution 9

$\lim_{x \to 2} \dfrac{1}{x - 2} (\dfrac{1}{x} - \dfrac{1}{2})$

$\lim_{x \to 2} \dfrac{1}{x - 2} (\dfrac{2 - x}{2x})$

$\lim_{x \to 2} \dfrac{1}{2x}$

Substituting $x$ with 2, we get $4$

* Solution 10

$\lim_{x \to \dfrac{\pi}{2}} \dfrac{sec x - tan x}{cos x}$

$\lim_{x \to \dfrac{\pi}{2}} \dfrac{(sec x - tan x)(sec x + tan x)}{cos x(sec x + tan x)}$

$\lim_{x \to \dfrac{\pi}{2}} \dfrac{(sec^2 x - tan^2 x)}{cos x(sec x + tan x)}$

$\lim_{x \to \dfrac{\pi}{2}} \dfrac{(sec^2 x - tan^2 x)}{cos x(sec x + tan x)}$

$\lim_{x \to \dfrac{\pi}{2}} \dfrac{1}{cos x(\dfrac{1}{cos x} + \dfrac{sin x}{cos x})}$

$\lim_{x \to \dfrac{\pi}{2}} \dfrac{1}{1 + sin x}$

Substituting $x$ with $\dfrac{\pi}{2}$, we get $\dfrac{1}{2}$
