#+LATEX_HEADER_EXTRA: \usepackage{indentfirst}
#+LATEX_HEADER_EXTRA: \require{physics}
#+LATEX_HEADER_EXTRA: \usepackage{amsmath}
#+OPTIONS: tex:t

* What does Limit mean ?

* Solution 1

  $f(x) = 3x - 2$
  
** Solution (a)

Suppose $0 < | x - 2 | < \dfrac{1}{6}$

$f(x) - 4 = | 3x - 6 | = | 3| |x - 2|$

We know that $| x - 2| < \dfrac{1}{6}$

$| 3|| x - 2| < \dfrac{1}{6} * 3$

$| 3|| x - 2| < \dfrac{1}{2}$

So, $f(x) - 4 < \dfrac{1}{2}$

** Soluion (b)

Suppose $0 < |x-2| < y$

$f(x) - 4 = |3||x - 2|$

We need to prove,

$f(x-4) < \dfrac{1}{10}$

$|3||x-2| < \dfrac{1}{10}$

Let's assume $y$ to be $\dfrac{1}{30}$.

We know that $|x - 2| < \dfrac{1}{30}$

$|3||x - 2| < \dfrac{1}{10}$

$f(x) - 4 < \dfrac{1}{10}$

* Solution 2

$g(x) = 5 - 2x$  

** Solution (a)

   Suppose $0 < |x - 1| < \dfrac{1}{2}$

   $|g(x) - 3| = |5 - 2x - 3| = |2 - 2x| = |2||1 - x| = |2||x - 1|$

   We know that $|x - 1| < \dfrac{1}{2}$

   |2|  |x-2| < 1

   |g(x) - 3| < 1

** Solution (b)

   Suppose $0 < |x - 1|< \dfrac{\epsilon}{2}$

   g(x) - 3 = |2}|1 - x}

   We know that $|x - 1|< \dfrac{\epsilon}{2}$

   |2}|x - 1|< \epsilon

   |g(x) - 3|< \epsilon

* Solution 3

  h(x) = \dfrac{3x^2 + 8x + 5}{x + 1}

  = \dfrac{3x^2 + 3x + 5x + 5}{x + 1}

  = \dfrac{3x(x + 1) + 5(x + 1)}{x + 1}

  = 3x + 5

** Solution (a)

   Suppose $0 < |x - (-1)|< \dfrac{1}{30}$

   Since $x - (-1) > 0$, $x \neq -1$. So $h(x)$ is defined.

   $h(x) - 2 = |3x + 5 - 2|= |3x + 3|= |3||x + 1|$

   Since $|x + 1|< \dfrac{1}{30}$

   $|3| |x + 1|< \dfrac{1}{10}$

   $|h(x) - 2|< \dfrac{1}{10}$

** Solution (b)

   Suppose $0 < |x + 1|< \dfrac{\epsilon}{3}$

   Since $|x - (-1)|> 0$, $x \neq -1$. So $h(x)$ is defined.

   $h(x) - 2 = |3||x + 1|$

   Since $|x + 1|< \dfrac{\epsilon}{3}$

   $|3||x + 1|< \epsilon$

   $|h(x) - 2|< \epsilon$

* Solution 4

f(x) = x.cos x

Suppose $0 < |x - 0|< \epsilon$

|f(x) - 0|= |x.cos x|= |x}|cos x}

Since $|x|< \epsilon$

|x}|cos x|< \epsilon.cos x

We know that the maximum value of $|cos x|\leq 1$. So,

|x}|cos x|< \epsilon.|cos x|\leq \epsilon

By [[https://en.wikipedia.org/wiki/Inequality_(mathematics)#Transitivity][Transitivity]], we infer that $|x||cos x|< \epsilon$

$|f(x) - 0|< \epsilon$

* Solution 5

  For graph (b) the $\epsilon - \delta$ criterion is true.

  For graph (c) the $\epsilon - \delta$ criterion is true. Note that
  even though the $f(a)$ in that graph lies in the forbidden region -
  we can ignore that point because for computing limits $x \neq a$

* Solution 6

  For graph (a). We certainly have *a* number $\delta$ such that the
  criterion is true.

  For graph (b), it's touching $L - \epsilon$ and hence the criterion
  is false.

  For graph (c), even for a slight $\epsilon$ - it goes into the
  forbidden region.

  For graph (d), we can ignore the f(x) value in the graph as by limit
  definition $x \neq a$. Now we can certainly find $\delta$ such that
  the criterion is true.

* Solution 7

  For graph (a) and (b) - From the definition of graph we know that $x
  \neq a$. So the value of the graph at $x = a$ need not be considered
  to see if they fall into the forbidden region. In graph (a) - we can
  see that as x -> a, f(x) -> L. But in graph (b), that's not the
  case. Hence for graph (a), $\lim_{x \to a} f(x) = L$

  For graph (c), we can chose a $\epsilon$ and also a very minimal
  $\delta$ such that it is true.

  For graph (d), we can chose a $\epsilon$ such that it goes into the
  forbidden region for the second part of the curve.

* Solution 8

  For no graph, it seems to be true as with a chosen $\epsilon$, it
  seems to go into the forbidden region.

* Solution 11

  (a) Yes. By the definition of limits, $\epsilon$ can be any
  arbitrary number greater than zero.

  (b) No. By decreasing $\delta$, the graph can go into the forbidden
  region.

  (c) No. By increase the $\delta$ and hence the x-coordinate - it can
  go into the forbidden region.

  (c) Yes. By decreasing the $\delta$ and hence the x-coordinate - it
  cannot go into the forbidden region if the criterion is already true.
