#+LATEX_HEADER_EXTRA: \usepackage{indentfirst}
#+LATEX_HEADER_EXTRA: \usepackage{amsmath}
#+LATEX_HEADER_EXTRA: \usepackage{mathmode}

* Limit Theorems

* Solution 1

Suppose $\epsilon > 0$. Let $\delta = \epsilon$. Suppose $0 < |x - 0| < \delta$.

$||x| - 0| = |x| < \delta < \epsilon$

* Solution 2

  Suppose $\lim_{x \to a} f(x) = 0$

  We know for $\forall \epsilon_{1} > 0 \; \exists \delta_{1} > 0 \; \forall x \; 0 < |x-a| < \delta_{1} \implies ||f(x)| - L| < \epsilon_{1}$

  Suppose $\epsilon > 0$.

  Let $\epsilon_{1} = \epsilon$. We know that there there $\exists \delta_{1} > 0 \; \forall x \; 0 < |x-a| < \delta_{1} \implies ||f(x)| - L| < \epsilon_{1}$

  Let's assume $\delta = \delta_{1}$. Suppose $0 < |x-a| < \delta$. Since $\delta = \delta_{1}$, we can infer that $|f(x)| - L < \epsilon_{1}$.

  Since $\epsilon_{1} = \epsilon$, we know that $||f(x)| - L| < \epsilon$.

  In our case, we know that $L$ is zero. So, $||f(x)| - 0| = ||f(x)|| = |f(x)| < \epsilon$

* Solution 3

  $\lim{x \to 3} x^3 - 5x^2 + 7x + 2$

  $= 3^3 - 5.3^2 + 7.3 + 2$

  $= 5$

* Solution 4

  $\lim{v \to -1}v^4 + 2v^3 + 3v^2 -v + 4$

  $= (-1)^4 + 2(-1)^3 + 3(-1)^2 -(-1) + 4$

  $= 1 - 2 + 3 + 1 + 4$

  $= 7$

* Solution 5

  $\lim_{v \to -1} v^100 + v^99 + v^98 + v^97 + ... + v^2 + v + 1$

  $= 50 - 50 + 1$

  $= 1$

* Solution 6

  $\lim_{x \to 4} \dfrac{x^2 - 3x - 4}{x - 2}$

  $= \dfrac{4^2 - 12 - 4}{4 - 2}$

  $= 0$

* Solution 7

  $\lim_{x \to 5}\dfrac{x^2 - 3x - 10}{x^2 - 5x}$

  $= \lim_{x \to 5}\dfrac{(x-5)(x+2)}{x(x-5)}$

  $= \lim_{x \to 5}\dfrac{x+2}{x}$

  $f_1(x) = \dfrac{x^2 - 3x - 10}{x^2 - 5x}$

  $f_2(x) = \dfrac{x + 2}{x}$

  For all $x$ except 5, $f_1(x) = f_2(x)$

  Also, $0 < |x-5| < 1$, So, $4 < x < 6$ and $x \neq 5$. So, $4 < x <
  6$. So, $x \neq 5$ and $x \neq 0$. Therefore $f_1(x)$ and $f_2(x)$
  are defined and equal.

  Using theorem 2.4.5,

  $\lim_{x \to 5}\dfrac{(x-5)(x+2)}{x(x-5)} = \lim_{x \to 5}\dfrac{x+2}{x} = \dfrac{7}{5}$

* Solution 8

  $\lim_{w \to -3} \dfrac{w^3 + 4w^2 + 3w}{w + 3}$

  The above limit can be reduced to $\lim{w \to -3} (w + 1)w$

  $f_1(x) = \dfrac{w^3 + 4w^2 + 3w}{w + 3}$

  $f_2(x) = (w + 1)w$

  For all $x$ except $-3$, $f_1(x) = f_2(x)$

  Suppose $0 < |w - (-3)| < 1$. We know that $w \neq -3$. So, $f_1(x)$
  and $f_2(x)$ are both defined. Using theorem 2.4.5,

  $\lim_{w \to -3} (w+1)w = (-3 + 1)(-3) = (-2)(-3) = 6$

* Solution 9

  $\lim_{x \to 2}\dfrac{x^2 + x - 6}{x^2 - x -2}$

  $f_1(x) = \dfrac{x^2 + x - 6}{x^2 - x -2}$

  $f_2(x) = \dfrac{x+3}{x+1}$

  Both $f_1(x)$ and $f_2(x)$ are same for all $x$ except $x = 2$ and
  $x = -1$. Suppose $0 < |x-2| < 1$. From that we know that $x \neq
  2$. Also, $1 < x < 3$. So, $x \neq 2$ and $x \neq -1$. So, both
  $f_1(x)$ and $f_2(x)$ are defined and equal.

  Using theorem 2.4.5,

  $\lim_{x \to 2} f_2(x) = \dfrac{5}{3}$

* Solution 10

  $\lim_{t \to 3}\dfrac{t^3 - 27}{t^2 - 9}$

  The above limits can be reduced to,

  $\lim_{t \to 3}\dfrac{t^2 + 9 + 3t}{t + 3}$

  From theorem 2.4.5,

  $\lim_{t \to 3}\dfrac{t^2 + 9 + 3t}{t + 3} = \dfrac{3^2 + 9 + 3^2}{6} = \dfrac{9}{2}$

* Solution 11

  $\lim_{x \to 2}\dfrac{x^2 - 2x}{x^2 - 4x + 4}$

  $= \lim_{x \to 2}\dfrac{x}{x-2}$

  $\lim_{x \to 2} x - 2 = 0$

  $\lim_{x \to 2} x = 2$

  From theorem 2.4.8, we can conclude that the limit is undefined.

* Solution 12

  $\lim_{x \to -1} \dfrac{ x + 4 - \dfrac{3}{x+2}}{x+1}$

  $= \lim_{x \to -1}\dfrac{x + 5}{x + 2}$

  From theorem 2.4.5,

  $\lim_{x \to -1}\dfrac{x + 5}{x + 2} = \dfrac{5-1}{2-1} = 4$

* Solution 13

  $\lim_{u \to 1}\dfrac{u - \dfrac{1}{u}}{1 - \dfrac{1}{u}}$

  $= \lim_{u \to 1}u + 1 = 2$

* Solution 14

  $\lim_{x \to -2}\dfrac{x}{x+2} - \dfrac{8}{x^2 - 4}$

  $= \lim{x \to -2}\dfrac{x^3 - 16x - 16}{(x+2)(x^2 - 4)}$

  $\lim_{x \to -2} x^3 - 16x - 16 = (-2)^3 + 32 - 16 = 8$

  $\lim_{x \to -2} (x+2)(x^2 - 4) = 0$

  From theorem 2.4.8, we can conclude that the limit is undefined.
