#+LATEX_HEADER_EXTRA: \usepackage{indentfirst}
#+LATEX_HEADER_EXTRA: \usepackage{amsmath}
#+LATEX_HEADER_EXTRA: \usepackage{mathmode}

* Solution 1

** Solution a

   Suppose $\lim_{x \to a^{-}} f(x) = L$ and $\lim_{x \to a^{-}} g(x) = M$

   We know that

   $\forall \epsilon > 0 \; \exists \delta_{1} > 0 \; \forall x a - \delta_{1} < x < a \implies |f(x)-L|<\epsilon$

   $\forall \epsilon > 0 \; \exists \delta_{2} > 0 \; \forall x a - \delta_{2} < x < a \implies |g(x)-M|<\epsilon$

   Suppose $\epsilon > 0$

   Applying above equation with $\dfrac{\epsilon}{2}$, we get
   
   $\exists \delta_{1} > 0 \; \forall x a - \delta_{1} < x < a \implies |f(x)-L|< \dfrac{\epsilon}{2}$

   $\exists \delta_{2} > 0 \; \forall x a - \delta_{2} < x < a \implies |g(x)-M|< \dfrac{\epsilon}{2}$

   Let $\delta = min(\delta_1, \delta_2)$. Then $\delta > 0, \delta \leq \delta_1$ and $\delta \leq \delta_2$

   Suppose $a - \delta < x < a$. Since $\delta \leq \delta_1$, we can infer that $a - \delta_1 \leq a - \delta$.

   So, $|f(x) - L| < \dfrac{\epsilon}{2}$

   Similarly, $|g(x) - M| < \dfrac{\epsilon}{2}$

   $f(x) + g(x) - L - M$

   $= |f(x) - L + g(x) - M|$

   $\leq |f(x)-L| + |g(x)-M|$ (From triangle inequality)

   $< \dfrac{\epsilon}{2} + \dfrac{\epsilon}{2}$

   $< \epsilon$

** Solution b

   Suppose $\lim_{x \to a^{+}} f(x) = L$ and $\lim_{x \to a^{+}} g(x) = M$

   We know from solution (a) that,

   $\lim_{x \to a^{+}} f(x) + g(x) = L + M$

   From the theorem, $\lim_{x \to a^{+}} cf(x) = cL$

   If $c = -1$, we know that $\lim_{x \to a^{+}} g(x) = -M$

   Therefore $\lim_{x \to a^{+}}  f(x)-g(x) = \lim_{x \to a^{+}}f(x) - \lim_{x \to a^{+}}g(x) = L - M$

** Solution c

   We need to use the same technique described in page 74 and 75. Thus
   we need to prove that $\lim_{x \to a^{+}}(f(x)-L)(g(x)-M) = 0$.

   We begin by assuming $\epsilon > 0$. We know that

   $a < x < a + \delta_{1} \implies |f(x) -> L| < \sqrt{\epsilon}$

   $a < x < a + \delta_{2} \implies |g(x) -> M| < \sqrt{\epsilon}$

   Let $\delta = min(\delta_1, \delta_2)$. Then $\delta > 0, \delta
   \leq \delta_1$ and $\delta \leq \delta_2$.

   Suppose $a < x < a + \delta$. Then $a < x < a + \delta_1$ and $a <
   x < a + \delta_2$. So,

   $|f(x)-L| < \sqrt{\epsilon}$

   $|g(x)-L| < \sqrt{\epsilon}$

   $(f(x) - L)(g(x) - M) = |f(x)-L||g(x)-M| < \sqrt{\epsilon}\sqrt{\epsilon} = \epsilon$

* Solution 2

** Solution a

   So suppose that as $x \to a^{-}$, $f_1(x) \to L$. To prove that as
   $x \to a^{-}$, $f_2(x) \to L$, we being as usual by assuming that
   $\epsilon > 0$. Since we have assumed that as $x \to a^{-}, f_1(x)
   \to L$, we know there is some number $\delta_1 > 0$ such that if
   $a - \delta_1 < x < a \implies |f_1(x)-L| < \epsilon$

   Now let $\delta = min(\delta_1, d)$ and suppose $a - \delta < x <
   a$. Then, $a - \delta_1 < x - a$. So, $|f_1(x)-L < \epsilon|$ and
   also $a-d < x < a$. So, $f_1(x) = f_2(x)$.

   Combining these two facts we conclude that $|f_2(x) - L| <
   \epsilon$ as required.

** Solution b

   So suppose that as $x \to a^{+}$, $f_1(x) \to L$. To prove that as
   $x \to a^{+}$, $f_2(x) \to L$ we begin as usual by assuming that
   $\epsilon > 0$. Since we have assumed that as $x \to a^{+}$,
   $f_1(x) \to L$, we know that there is some number $\delta_1 > 0$
   such that $a < x < a + \delta_1$, then $|f_1(x)-L| < \epsilon$.

   Now let $\delta = min(\delta_1, d)$ and suppose that $a < x <
   a+\delta$. Since $\delta <= \delta_1$ we know $a < x <
   a+\delta_1$. Since $\delta <= \delta_1$ we know that $a < x < a +
   \delta_1$. So, $|f_1(x) - L| < \epsilon$. Also, $a < x < a + d$,
   So, $f_1(x) = f_2(x)$. Combining these two we can conclude that
   $|f_2(x)-L| < \epsilon$ as required.

* Solution 3

   We need to prove here that if $\lim_{x \to a} f(x) = L$ then
   $\lim_{x \to a^{-} f(x)} = L$ and $\lim_{x \to a^{+}} f(x) = L$.

   Suppose $\lim_{x \to a} f(x) = L$. So,

   $\forall \epsilon > 0 \; \exists \delta_1 > 0 \; \forall x a - \delta_1 < x < a + \delta_1 \implies |f(x)-L|<\epsilon$

   Let's prove $\lim_{x \to a^{-}} f(x) = L$

   Suppose $\delta = \delta_1 > 0$
   Suppose $a - \delta_1 < x < a$

   Since $\delta_1 > 0$ and $\delta_1 + a > a$. So, $a - \delta_1 < x < a + \delta_1$. So, $f(x) - L < \epsilon$

   Let's prove $\lim_{x \to a^{+}} f(x) = L$

   Suppose $\delta = \delta_1 > 0$

   Suppose $a < x < a + \delta_1$

   We know that $\delta_1 > 0$, So, $-\delta_1 < 0$. So, $a - \delta_1 < a$. So, $a - \delta_1 < a < x < a + \delta_1$. So, we can infer that $|f(x)-L|<\epsilon$

* Solution 4

  $\lim_{x \to \infty} \dfrac{3x^2+1}{x^2-3}$

  $= \lim_{x \to \infty} \dfrac{3 + \dfrac{1}{x^2}}{1 - \dfrac{3}{x^2}} = \dfrac{3}{1} = 3$

* Solution 5

  $\lim_{t \to -\infty} \dfrac{100t^2 + 1}{2t^{100} - 1}$

  $= \lim_{t \to -\infty} \dfrac{t^2(100 + \dfrac{1}{t^2})}{t^100(2 - \dfrac{1}{t^100})} = 0$

* Solution 6

  $\lim_{x \to \infty}\dfrac{3-x^2}{2x^2 + 7x}$

  $= \lim_{x \to \infty} \dfrac{x^2(\dfrac{3}{x^2} - 1)}{x^2(2 + \dfrac{7}{x})}$

  $= \dfrac{0 - 1}{2 + 0} = -\dfrac{1}{2}$

* Solution 7

  $\lim_{x \to \infty} x^2 - \dfrac{x^4}{x^2 + 3}$

  $= \lim_{x \to \infty} \dfrac{3x^2}{x^2 + 3}$

  $= \dfrac{3x^2}{x^2(1 + \dfrac{3}{x^2})} = \dfrac{3}{1}$

* Solution 8

  $\lim_{x \to \infty} \dfrac{x^2-2}{x} - \dfrac{x^2}{x+3}$

  $= \lim_{x \to \infty} \dfrac{x^2(3 - \dfrac{2}{x} - \dfrac{6}{x^2})}{x^2(1 + \dfrac{3}{x})}$

  $= \dfrac{3}{1} = 3$

* Solution 9

  $\lim_{x \to \infty} x^2(\dfrac{2}{2x-1} - \dfrac{1}{x-1})$

  $= \lim_{x \to \infty} x^2(\dfrac{-1}{2x^2 - 3x + 1})$

  $= \lim_{x \to \infty} \dfrac{-x^2}{x^2(2 - \dfrac{3}{x} + \dfrac{1}{x^2})}$

  $= \dfrac{-1}{2 -0 + 0} = -\dfrac{1}{2}$

* Solution 10

  $\lim_{r \to -\infty} \dfrac{r + \dfrac{1}{r}}{r - \dfrac{1}{r^2}}$

  $\lim_{r \to -\infty} \dfrac{r(1 + \dfrac{1}{r^2})}{r(1 - \dfrac{1}{r^3})}$

  $= \dfrac{1 + 0}{1 - 0} = 1$

* Solution 11

  $\lim_{x \to -\infty} x^5 + 100x^4$

  $= -\infinity + 100 \infty$

  So, the above limits are undefined.

* Solution 12

  $\lim_{x \to \infty} \dfrac{cos(x-7)}{x^2 - 7x}$

  $\lim_{x \to \infty} = \dfrac{1}{x^2 - 7x} = \lim_{x \to \infty} \dfrac{1}{x^2(1 - \dfrac{7}{x})} = 0$

  $\lim_{x \to \infty} cos (x - 7)$ will be from $[-1,1]$.

  From theorem 2.4.8, we can infer that the whole limit tends to zero.

* Solution 13

  $\lim_{z \to -\infty} z^2 + sin z$

  $\lim_{z \to -\infty} z^2 = \infty$

  We know that the range of $sin x$ is $[-1,1]$. So, the limit will be $\infty$.

* Solution 14

  $\lim_{z \to -\infty} z(sin z + 3)$

  $= -\infty(sin -\infty + 3) = -\infty$

* Solution 15

  $\lim_{x \to \infty} \dfrac{(2+x)sin^2 x}{x^2(2 + sin x)}$

  $= \lim_{x \to \infty} \dfrac{(\dfrac{2}{2} + 1)sin^2 x}{x(2 + sin x)}$

  $= 0$

* Solution 16

  $\lim_{x \to 0^+}\dfrac{x^2 - 5}{x}$

  $= \lim_{x \to 0^+}x(1 - \dfrac{5}{x}) = -\infty$

* Solution 17

  $\lim_{x \to 0^-} \dfrac{1}{x^2 - 5x}$

  $= \lim_{x \to 0^-} \dfrac{1}{x^2(1 - \dfrac{5}{x})}$

  $= \infty$

* Solution 18

  $\lim_{u \to 3^{-}} \dfrac{u^2 - 3u}{|u - 3|}$

  $|u-3| = -(u-3)$

  $\lim_{u \to 3^{-}} \dfrac{u^2-3u}{-(u-3)}$

  $= \lim_{u \to 3^{-}} \dfrac{u}{-1} = -3$

* Solution 19

  $\lim_{x \to 2^+} \dfrac{x + |2-x| - 2}{x^2 + 3x - 10}$

  $|2 - x| = -(2 - x)$

  $\lim_{x \to 2^+} \dfrac{2}{x+5} = \dfrac{2}{2 + 5} = \dfrac{2}{7}$

* Solution 20

  $\lim_{x \to \infty} \dfrac{2x}{1 + |x|}$

  $= \lim_{x \to \infty} \dfrac{2x}{1 + x}$

  $= \lim_{x \to \infty} \dfrac{2}{\dfrac{1}{x} + 1}$

  $= \dfrac{2}{0 + 1} = 2$

* Solution 21

  $\lim_{x \to -\infty} \dfrac{2x}{1 + |x|}$

  $=\lim_{x \to -\infty} \dfrac{2x}{1 - x} $

  $= \lim_{x \to -\infty} \dfrac{2x}{x(\dfrac{1}{x} - 1)}$

  $= \dfrac{2}{-1} = -2$

* Solution 22

  $\lim_{t \to -1^-} \lfloor 2t + 1 \rfloor$

  $= \lfloor -2 + 1 \rfloor$

  $= \lfloor -1 \rfloor$

  $= -2$

* Solution 23

  $\lim_{w \to 2^-} \dfrac{w^2-4}{w - 2\lfloor w \rfloor}$

  $\lim_{w \to 2^-} \lfloor w \rfloor = 1$

  $= \lim_{w \to 2^-} \dfrac{w^2-4}{w - 2}$

  $= \lim_{w \to 2^-} w+2$

  $= 4$

* Solution 24

  $\lim_{w \to 2^+} \dfrac{f(3-x) - 2}{x - 2}$

  In our case,

  $f(x) = x + 2$
  $f(3 - x) = 3 - x + 2 = 4 - x$

  $\dfrac{4 - x - 2}{x - 2} = \dfrac{2-x}{x-2} = - 1$

* Solution 25

  Todo

* Solution 26

  $\lim_{x \to 1^+} \dfrac{x^2 + |x-1| - 1}{x^2 + |x-2| - 2}$

  $\lim_{x \to 1^+} |x-1| = x - 1$

  $\lim_{x \to 1^+} |x-2| = -(x-2) = 2-x$

  $\lim_{x \to 1^+} \dfrac{x+2}{x} = \dfrac{3}{1} = 3$

* Solution 27

  $\lim_{x to -2^{+}} \dfrac{|x^2 + 2x|}{3x^2 + 5x - 2}$

  $|x^2 + 2x| = |x(x+2)| = -x(x+2)$

  $\lim_{x to -2^{+}} \dfrac{-x(x+2)}{(3x-1)(x+2)}$

  $= \lim_{x to -2^{+}} \dfrac{-x}{3x - 1}$

  $= \dfrac{-(-2)}{3(-2) - 1}$

  $= \dfrac{2}{-6 - 1}$

  $= \dfrac{-2}{7}$

* Solution 28

  We need to prove that $\lim_{x \to a} f(x) = \infty$

  In other words, $\forall M \; \exists \delta > 0 \; \forall x 0 < |x-a| < \delta \implies f(x) > M$

  Suppose M.

  Since $\lim_{x \to a} g(x) = \infty$, there is some $\delta_1 > 0$ such that $0 < |x-a| < \delta_1 \implies g(x) > M$

  Let $\delta = min(\delta_1, d)$. So, $\delta > 0, \delta \leq \delta_1$ and $\delta \leq d$.

  Suppose $0 < |x-a| < delta$. Since $\delta \leq \delta_1$, we infer that $0 < |x-a| < \delta_1$.

  From our initial proposition, we can infer that $g(x) > M$.

  Since $\delta \leq d$, we infer that $0 < |x-a| < d$. So, $f(x) \geq g(x)$.

  So, $f(x) \geq g(x) > M$. So, $f(x) > M$.

* Solution 29

  $\lim_{x \to -\infty} x = -\infty$

  In other words, we need to prove that

  $\forall M \; \exists N \; \forall x x < N \implies x < M$

  Suppose M be an arbitray number.

  Let $N = M$

  Suppose $x < N$.

  Since $N = M$, we infer $x < M$.

* Solution 30

  Given $c$, we need to find $f$ and $g$ such that

  $\lim_{x \to 0}f(x) = \infty$

  $\lim_{x \to 0}g(x) = 0$

  $\lim_{x \to 0}f(x)g(x) = c$

  $f(x) = \dfrac{c}{|x|}$

  $g(x) = |x|$

  The above functions satisfy the criteria.
