#+LATEX_HEADER_EXTRA: \usepackage{indentfirst}
#+LATEX_HEADER_EXTRA: \usepackage{amsmath}

* Solution 1

$(\dfrac{50n}{n^2 - 8n + 17})_{n=1}^{\infty}$

Let $f(n) = \dfrac{50n}{n^2 - 8n + 17}$

$f(1) = \dfrac{50}{1^2 - 8 + 17} = \dfrac{50}{10} = 5$

$f(2) = \dfrac{50.2}{2^2 - 16 + 17} = \dfrac{50.2}{4+1} = \dfrac{50.2}{5} = 20$

$f(n) = \dfrac{50n}{(n-4)^2 + 1}$

$f(3) = \dfrac{50.3}{1^2 + 1} = \dfrac{50.3}{2} = 25.3 = 75$

$f(4) = \dfrac{50.4}{1} = 200$

From theorem 2.8.2, $\lim_{n \to \infty} \dfrac{50n}{(n-4)^2 + 1}$

$= \lim_{n \to \infty} \dfrac{50n}{n^2(1 - \dfrac{4}{n})^2 + 1}$

$= \lim_{n \to \infty} \dfrac{50}{n((1-\dfrac{4}{n})^2 + \dfrac{1}{n})}$

$= 0$

* Solution 2

$(\dfrac{1 + (-1)^n}{n})_{n=1}^{\infty}$

Let $f(n) = \dfrac{1 + (-1)^n}{n}$

$f(1) = \dfrac{1 + (-1)^1}{1} = \dfrac{1-1}{1} = 0$

$f(2) = \dfrac{1 + (-1)^2}{2} = \dfrac{1+1}{2} = 1$

$f(3) = \dfrac{1 + (-1)^3}{3} = \dfrac{1-1}{3} = 0$

$f(4) = \dfrac{1 + (-1)^4}{4} = \dfrac{1+1}{4} = \frac{1}{2}$

From theorem 2.8.2, $\lim_{n \to \infty} \dfrac{1 + (-1)^n}{n}$

$= \lim_{n \to \infty} \dfrac{1}{n} + \lim_{n \to \infty} \dfrac{-1^n}{n}$

$= 0 + 0 = 0$

* Solution 3

$(sin (\pi n))_{n=3}^{\infty}$

Let $f(n) = sin (\pi n)$

$f(3) = sin 3\pi = sin \pi = 0$

$f(4) = sin 4\pi = sin 0 = 0$

$f(5) = sin 5\pi = sin \pi = 0$

$f(6) = sin 6\pi = sin 0 = 0$

$\lim_{n \to \infty} sin (\pi n)$

We know that $n$ starts from $3$.

Since function  is periodic at $2\pi$,

$\lim_{n \to \infty} sin (\pi n) = 0$

* Solution 4

$\lim_{n \to \infty} \dfrac{3n^2 - 1}{n^2 + 3}$

From theorem 2.8.2,

$\lim_{n \to \infty} \dfrac{3n^2 - 1}{n^2 + 3} = \dfrac{3-0}{1+0} = 3$

* Solution 5

$\lim_{n \to \infty} (\dfrac{n^2}{n+1} + \dfrac{4-n^3}{n^2-1})$

From theorem 2.8.2,

$\lim_{n \to \infty} (\dfrac{n^2}{n+1} + \dfrac{4-n^3}{n^2-1})$

$= \lim_{n \to \infty} (\dfrac{n^2(n-1) + (4-n^3)}{(n+1)(n-1)}$

$= \lim_{n \to \infty} \dfrac{4-n^2}{(n+1)(n-1)}$

$= \lim_{n \to \infty} \dfrac{\dfrac{4}{n^2} - 1}{(1 + \dfrac{1}{n})(1-\dfrac{1}{n})}$

$= \dfrac{-1}{(1+0)(1-0)} = -1$

* Solution 6

$\lim_{n \to \infty} (n^3(\dfrac{1}{n^2} - \dfrac{1}{(n+1)^2}))$

From theorem 2.8.2,

$\lim_{n \to \infty} (n^3(\dfrac{(n+1)^2}{n^2(n+1)^2} - \dfrac{n^2}{n^2(n+1)^2}))$

$= \lim_{n \to \infty} (n^3(\dfrac{(n+1)^2 - n^2}{n^2(n+1)^2}$

$= \lim_{n \to \infty} (n(\dfrac{n^2 + 1 + 2n - n^2}{(n+1)^2}$

$= \lim_{n \to \infty} (n(\dfrac{(1+2n)}{(n+1)^2}$

$= \lim_{n \to \infty} ((\dfrac{n^2(1/n+2)}{n^2(1+1/n)^2}$

$= \dfrac{0+2}{1+0} = 2$

* Solution 7

$\lim_{n \to \infty} \dfrac{n \sin n}{n^2 + 1}$

From theorem 2.8.2,

$\lim_{n \to \infty} \dfrac{n}{n^2(1 + \dfrac{\sin n}{n^2})}$

$= \lim_{n \to \infty} \dfrac{1}{n(1 + \dfrac{\sin n}{n^2})}$

$= 0$

* Solution 8

$\lim_{n \to \infty} \dfrac{n}{n^2 + \sin n}$

From theorem 2.8.2,

$\lim_{n \to \infty} \dfrac{n}{n^2(1 + \sin n/n^2)}$

$= 0$

* Solution 9

$\lim_{n \to \infty} \dfrac{1}{(3 + (-1)^n)^n}$

When $n$ is even, $(-1)^n$ is positive one.

When $n$ is odd, $(-1)^n$ is negative one.

But in both cases,

$(3 + (-1)^n)$ is positive.

When $n$ is even, the value is $\dfrac{1}{4^n} = \dfrac{1}{2^{2n}}$

When $n$ is odd, the value is $\dfrac{1}{2^n}$

We can observe that as $n \to \infty$, the function tends to zero.

$\lim_{n \to \infty} \dfrac{1}{2^n} = 0$

$\lim_{n \to \infty} \dfrac{1}{2^{2n}} = 0$

* Solution 10

  $\lim_{n \to \infty} \dfrac{1}{(2 + (-1)^n)^n} = 0$

  When $n$ is even, $(-1)^n$ is positive.

  When $n$ is odd, $(-1)^n$ is negative.

  Overall, $2 + (-1)^n$ can be either $3$ or $1$ based on either $n$
  is even or odd.

  When $n$ is even,

  $\lim_{n \to \infty} \dfrac{1}{3^n}$

  Let $u = f(n) = 3^n$

  As $n \to \infty$, $u \to \infty$

  $\lim_{u \to \infty} \dfrac{1}{u} = 0$

  When $n$ is odd,

  $\lim_{n \to \infty} \dfrac{1}{1^n} = 1$

  So, the limit is undefined as it oscillates between $0$ and $1$.

* Solution 11

  $\lim_{n \to \infty} \dfrac{1}{2^n + (-1)^n}$

  When $n$ is even, $(-1)^n$ is 1.

  When $n$ is odd, $(-1)^n$ is $-1$.

  When $n$ is even,

  $\lim_{n \to \infty} \dfrac{1}{2^n + 1}$

  Let $u = f(n) = 2^n + 1$

  As $n \to \infty$, $u \to \infty$

  $\lim_{u \to \infty} \dfrac{1}{u} = 0$

  When $n$ is odd,

  $\lim_{n \to \infty} \dfrac{1}{2^n - 1}$

  Let $u = f(n) = 2^n - 1$

  As $n \to \infty$, $u \to \infty$

  As $u \to \infty, \dfrac{1}{u} \to 0$

  So, $\lim_{n \to \infty} \dfrac{1}{2^n - 1} = 0$

  So, $\lim_{n \to \infty} \dfrac{1}{2^n + (-1)^n} = 0$  

* Solution 12

  $\lim_{n \to \infty} (\sqrt{n^3 + n} - \sqrt[n]{n})$

  $= \lim_{n \to \infty} n(\sqrt{n + \dfrac{1}{n}} - \sqrt[n]{\dfrac{1}{n-1}})$

  $= \infty$

  
* Solution 13

  $\lim_{n \to \infty} (\sqrt{n^3 + n^2} - \sqrt[n]{n})$

  $= \lim_{n \to \infty} n(\sqrt{n + 1} - \sqrt[n]{\dfrac{1}{n-1}})$

  $= \infty$

* Solution 14

  $\lim_{n \to \infty} \sin (\dfrac{(2n-1)\pi}{2})$

  $= \lim_{n \to \infty} \sin (n\pi - \dfrac{\pi}{2})$

  $= -\lim_{n \to \infty} \cos n\pi$

  This means that the limit value will be oscillating between $1$ and
  $-1$. So it is undefined.

* Solution 15

  $\lim_{n \to \infty} \sin (\dfrac{(4n-1)\pi}{2})$

  $= \lim_{n \to \infty} \sin (2n\pi - \dfrac{\pi}{2})$

  $= - \lim_{n \to \infty} \cos 2n\pi$

  Since $\cos$ function is periodic at $2\pi$,

  $- \lim_{n \to \infty} \cos 2n\pi = -1$

* Solution 16

  $\lim_{n \to \infty} \sin (\dfrac{6\pi n^2}{3n+1})$

  Let $u = f(n) = \dfrac{6\pi n^2}{3n+1}$

  $\lim_{n \to \infty} f(n) = \lim_{n \to \infty} \dfrac{n^2(6\pi)}{n^2(\dfrac{3}{n} + \dfrac{1}{n^2})}$

  $= \lim_{n \to \infty} \dfrac{6\pi}{\dfrac{3}{n} + \dfrac{1}{n^2}} = \infty$

  As $n \to \infty$, $u \to \infty$

  $\lim_{u \to \infty} \sin u $
  
  The limit diverges and hence it is not defined.
