#+LATEX_HEADER_EXTRA: \usepackage{indentfirst}
#+LATEX_HEADER_EXTRA: \usepackage{amsmath}

* Solution 1

$(\dfrac{2n-1}{n})_{n=1}^\infty$

$a_n = \dfrac{2n-1}{n}$

$a_{n+1} = \dfrac{2(n+1)-1}{n+1} = \dfrac{2n+2-1}{n+1} = \dfrac{2n+1}{n+1}$

$a_{n+1} - a_n = \dfrac{2n+1}{n+1} - \dfrac{2n-1}{n}$

$= \dfrac{(2n+1)n - (2n-1)(n+1)}{(n+1)n}$

$= \dfrac{2n^2 + n - (2n^2 -n + 2n -1)}{(n+1)n}$

$= \dfrac{1}{(n+1)n}$

For $n \geq 1$, we know that $\dfrac{1}{n(n+1)} > 0$.

So, $a_{n+1} > a_n$

Hence we conclude that the sequence is strictly increasing.

* Solution 2

  $(\dfrac{n}{2n+1})_{n=1}^\infty$

  $a_n = \dfrac{n}{2n+1}$

  $a_{n+1} = \dfrac{n+1}{2(n+1)+1} = \dfrac{n+1}{2n+3}$

  $a_{n+1}-a_n = \dfrac{n+1}{2n+3} - \dfrac{n}{2n+1}$

  $= \dfrac{(n+1)(2n+1)-n(2n+3)}{(2n+3)(2n+1)}$

  $= \dfrac{2n^2+n+2n+1-2n^2-3n}{(2n+3)(2n+1)}$

  $= \dfrac{1}{(2n+3)(2n+1)}$

  For $n \geq 1$, we know that $\dfrac{1}{(2n+3)(2n+1)} > 0$.

  So, $a_{n+1} > a_n$

  Hence we conclude that the sequence is strictly increasing.

* Solution 3

  $(n^2 - 2n)_{n=1}^\infty$

  $a_n = n^2 - 2n$

  $a_{n+1} = (n+1)^2 - 2(n+1)$

  $= n^2 + 1 + 2n - 2n -2$

  $= n^2 - 1$

  $a_{n+1} - a_n = n^2 - 1 -(n^2 - 2n)$

  $= 2n - 1$

  For $n \geq 1$, we know that $2n-1 > 0$.

  So, $a_{n+1} > a_n$.

  Hence we conclude that the sequence is strictly increasing.

* Solution 4

  $(n^2-3n)_{n=1}^\infty$

  $a_n = n^2 - 3n$

  $a_{n+1} = (n+1)^2 - 3(n+1)$

  $= n^2 + 2n + 1 -3n - 3$

  $= n^2 - n - 2$

  $a_{n+1}-a_n = n^2 - n - 2 - n^2 + 3n$

  $= 2n - 2 = 2(n-1)$

  For $n \geq 1, 2(n-1) \geq 0$

  So, $a_{n+1} \geq a_n$

  Hence we conclude that the sequence is weakly increasing.

* Solution 5

  $(n^2 - 4n)_{n=1}^\infty$

  $a_n = n^2 - 4n$

  $a_{n+1} = (n+1)^2 - 4(n+1)$

  $= n^2 + 1 + 2n - 4n - 4$

  $= n^2 + 1 - 2n -4 = n^2 - 2n -3$

  $a_{n+1} - a_n = n^2 - 2n - 3 - n^2 + 4n$

  $= 2n - 3$

  When $n = 1, 2n - 3 < 0$.

  When $n = 2, 2n - 3 > 0$.

  So, the sequence diverges.

* Solution 6

  $(\dfrac{2^{3n+1}}{3^{2n+1}})_{n=1}^\infty$

  $a_n = \dfrac{2^{3n+1}}{3^{2n+1}}$

  $a_{n + 1} = \dfrac{2^{3(n+1)+1}}{3^{2(n+1)+1}} = \dfrac{2^{3n+4}}{3^{2n + 3}}$

  $\dfrac{a_{n+1}}{a_n} = \dfrac{2^{3n+4}.3^{2n+1}}{2^{3n+1}.3^{2n+3}}$

  $= 2^{3n + 4 - 3n -1}.3^{2n+1-2n-3}$

  $= 2^3.3^{-2}$

  $= \dfrac{8}{9}$

  So, $\dfrac{a_{n+1}}{a_n} = \dfrac{8}{9}$

  $\dfrac{a_n}{a_{n+1}} = \dfrac{9}{8}$

  We know that $\dfrac{9}{8} > 1$

  So, $a_n > a_{n+1}$

  Hence we conclude that the sequence is strictly decreasing.

* Solution 7

  $(\dfrac{(2n)!}{4^n(n!)^2})_{n=1}^\infty$

  $a_n = \dfrac{(2n)!}{4^n(n!)^2}$

  $a_{n+1} = \dfrac{(2(n+1))!}{4^{n+1}((n+1)!)^2}$

  $= \dfrac{(2n)!(2n+2)(2n+1)}{4.4^n((n+1)(n)!)^2}$

  $\dfrac{a_{n+1}}{a_n} = \dfrac{(2n)!(2n+2)(2n+1)}{4.4^n((n+1)(n)!)^2} * \dfrac{4^n(n!)^2}{(2n)!}$

  $= \dfrac{(2n+2)(2n+1)}{4(n+1)^2}$

  $= \dfrac{2(2n+1)}{4(n+1)} = \dfrac{2n+1}{2(n+1)} = \dfrac{2n+1}{2n+2}$

  So, $\dfrac{a_{n+1}}{a_n} = \dfrac{2n+1}{2n+2}$

  Since $2n+2 > 2n+1$

  $\dfrac{2n+2}{2n+1} > 1$

  So, $a_{n+1} > a_n$

  Hence we conclude that the sequence is strictly increasing.

* Solution 8

  $(\dfrac{(3n)!n!}{((2n)!)^2})_{n=1}^\infty$

  $a_n = \dfrac{(3n)!n!}{((2n)!)^2}$

  $a_{n+1} = \dfrac{(3(n+1)!(n+1)!}{((2(n+1))!)^2}$

  $= \dfrac{(3n+3)(3n+2)(3n+1)(3n)!(n+1)n!}{((2n+2)(2n+1)(2n)!)^2}$

  $\dfrac{a_{n+1}}{a_n} = \dfrac{(3n+3)(3n+2)(3n+1)(n+1)}{((2n+2)(2n+1))^2}$

  $= \dfrac{3(n+1^2)(3n+1)(3n+2)}{(2n+2)^2(2n+1)^2}$

  $= \dfrac{3(3n+1)(3n+2)}{4(2n+1)^2}$

  We know that $2n+1 < 3n+1$ and also $2n + 1 < 3n + 2$

  So, $(2n+1)^2 < (3n+1)(3n+2)$

  So, $\dfrac{(3n+1)(3n+2)}{(2n+1)^2} > 1$

  $\dfrac{3(3n+1)(3n+2)}{4(2n+1)^2} > \dfrac{3}{4}$

  So, $\dfrac{a_{n+1}}{a_n} > \dfrac{3}{4}$

  $\dfrac{a_n}{a_{n+1}} > \dfrac{4}{3}$

  So, $a_n > a_{n+1}$

  Hence we conclude that the sequence is strictly decreasing.

* Solution 9

  $(sin(\dfrac{n\pi}{4}))_{n=1}^\infty$

  $a_n = \sin(\dfrac{n\pi}{4})$

  $a_{n+1} = \sin(\dfrac{(n+1)\pi}{4}) = \sin (\dfrac{n\pi}{4} + \dfrac{\pi}{4})$

  $a_1 = sin (\dfrac{\pi}{4})$

  $a_2 = sin (\dfrac{2\pi}{4})$

  $a_3 = sin (\dfrac{3\pi}{4})$

  $a_4 = sin (\dfrac{4\pi}{4})$

  Since the $\sin$ function oscillates up and down between $-1$ and
  $1$ as $n \to \infty$, we can say that the sequence diverges.

  
  
