#+LATEX_HEADER_EXTRA: \usepackage{indentfirst}
#+LATEX_HEADER_EXTRA: \usepackage{amsmath}

* Solution 1

$\lim_{x \to \infty} \dfrac{\dfrac{1}{x} - 7}{x^3 - x^2}$

$=  \lim_{x \to \infty} \dfrac{\dfrac{1}{x} - 7}{x^3(1 - \dfrac{1}{x})}$

$\lim_{x \to \infty} \dfrac{1}{x} - 7 = -7$

$\lim_{x \to \infty} 1 - \dfrac{1}{x} = 1 - 0 = 1$

$\lim_{x \to \infty} \dfrac{1}{x^3} = 0$

Combining them, $\dfrac{0.(-7)}{1} = 0$

* Solution 2

$\lim_{x \to 3^-} \dfrac{x-2}{x-3}$

The numerator approaches 1 and the denominator approaches 0, so the
limit is undefined. (From Theorem 2.4.8)

As $x \to 3^-$, $x - 3 \to 0^-$

By part 2 of Theorem 2.6.2, as $x \to 3^{\neq}$, $\dfrac{1}{x-3} \to -\infty$

So, $\lim_{x \to 3^-} \dfrac{x-2}{x-3} = -\infty$

* Solution 3

$\lim_{x \to 3^-} \dfrac{x-4}{x-3}$

The numerator approaches -1 and the denominator approaches 0, so the
limit is undefined. (From Theorem 2.4.8)

As $x \to 3^-$, $x - 3 \to 0^-$. 

By part 2 of Theorem 2.6.2, as $x \to 3^{\neq}$, $\dfrac{1}{x-3} \to -\infty$

Combining this with the fact as $x \to 3^-$, $x-4 \to -1$, we can use
theorem 2.5.14,

$\lim_{x \to 3^-} \dfrac{x-4}{x-3} = \infty$

* Solution 4

$\lim_{t \to 0^+} \dfrac{t^2 + 3t}{t^3 - t^2}$

$= \lim_{t \to 0^+} \dfrac{t + 3}{t(t-1)}$

The numerator approaches 3 and the denominator approaches 0, so the
limit is undefined. (From Theorem 2.4.8)

As $t \to 0^+$, $t(t-1) \to 0^-$.

By part 2 of Theorem 2.6.2, as $t \to 0^{\neq}$, $\dfrac{1}{t(t-1)}
\to -\infty$

So, $\lim_{t \to 0^+} \dfrac{t^2 + 3t}{t^3 - t^2} = -\infty$

* Solution 5

$\lim_{x \to 1^-} \dfrac{x^2 - x + 2}{x^2 + x - 2}$

The numerator approaches 2 and the denominator approaches 0, so the
limit is undefined. (From Theorem 2.4.8)

As $x \to 1^-$, $x^2 + x - 2 \to 0^-$. From theore 2.6.2, as $x \to
1^-$, $\dfrac{1}{x^2 + x - 2} \to -\infty$.

So, $\lim_{x \to 1^-} \dfrac{x^2 - x + 2}{x^2 + x - 2} = -\infty$

* Solution 6

$\lim_{v \to 1}\dfrac{v^2 - 3v + 1}{v^2 - 2v + 1}$

The numerator approaches -1 and the denominator approaches 0, so the
limit is undefined. (From Theorem 2.4.8)

As $v \to 1$, $v^2 - 2v + 1 \to 0^+$. From theorem 2.6.2 as $v \to 1$,
$\dfrac{1}{v^2 - 2v + 1} \to \infty$.

As $v \to 1^+, v^2 - 3v + 1 \to -1^-$
As $v \to 1^-, v^2 - 3v + 1 \to -1^+$

$\lim_{v \to 1}\dfrac{v^2 - 3v + 1}{v^2 - 2v + 1} = -\infty$

* Solution 7

$\lim_{v \to 1}\dfrac{v^2 - 3v + 2}{v^2 - 2v + 1}$  
