* The Chain Rule

** Theorem 3.4.1 (Chain Rule)

If $g$ is differentiable at $x$ and $f$ is differentiable at $g(x)$,
then $f \circ g$ is differentiable at $x$, and

$(f \circ g)'(x) = f'(g(x))g'(x)$

In other words,

$\dfrac{d}{dx} (f(g(x))) = f'(g(x))\dfrac{d}{dx}(g(x))$

We can streamline our use of the chain rule by noticing the
relationship between the following two equations:

$\dfrac{d}{dx}(f(x)) = f'(x)$

$\dfrac{d}{dx} (f(g(x))) = f'(g(x))\dfrac{d}{dx}(g(x))$

The first equations says that the derivation of $f(x)$ is
$f'(x)$. Replacing $x$ with the expression $g(x)$ on both sides, you
might expect that the derivative of $f(g(x))$ would be $f'(g(x))$. The
chain rule says that this is part of the answer, but it's not the
whole thing. To get the correct answer you need to multiply by the
derivative of $g(x)$

** Theorem 3.4.4

Suppose $f(x) = x^r$, where $r$ is a nonzero rational number. Then
$f'(x) = rx^{r-1}$.

Since $r$ is rational and $r \neq 0$, we can write $r=m/n$, where $n$
is a positive integer, $m$ is a nonzero integer, and the fraction
$m/n$ is reducted to lowest terms. If $n$ is even, then the domain of
$f'$ is $(0,\infty)$. If $n$ is odd and $r<1$, then the domain of $f'$
is $(-\infty,0) \cup (0,\infty)$. And if $n$ is odd and $r \geq 1$
then the domain of $f'$ is $(-\infty,\infty)$

** Higher order derivatives

If $f$ is a function, then its derivative $f'$ is also a function. The
derivative of $f'$ is written as $f''$; it's called the second
derivative of $f$. If we differentiate $f$ $n$ times, then we get the
$n$ th derivative of $f$, which is denoted $f^{(n)}$. These are called
*higher-order derivatives$ of $f$.

*** Leibniz notation for higher order derivatives

If $y = f(x)$, then $dy/dx = f'(x)$. Therefore,

$f''(x) = \dfrac{d}{dx}(f'(x)) = \dfrac{d}{dx}(\dfrac{dy}{dx})$

$f^{(n)}(x) = \dfrac{d^ny}{dx^n} = \dfrac{d^n}{dx^n}(f(x))$


