* Derivatives

** Solution 1

   $f(x) = 3-x^2$

   $f'(x) = \lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}$

   $f(x+h) = 3-(x+h)^2 = 3-(x^2+h^2+2xh)$

   $f(x) = 3-x^2$

   $f(x+h)-f(x) = 3-x^2-h^2-2xh-3+x^2$

   $= -h^2 - 2xh$

   $\lim_{h \to 0} \dfrac{-h^2-2xh}{h} = \lim_{h \to 0} -h - 2x$

   $= -2x$

** Solution 2

   $g(x) = x^2 - 3x + 2$

   $g'(x) = \lim_{h \to 0} \dfrac{g(x+h)-g(x)}{h}$

   $g(x+h) = (x+h)^2 - 3(x+h) + 2$

   $= x^2 + h^2 +2xh -3x -3h + 2$

   $g(x) = x^2-3x+2$

   $g(x+h)-g(x)=x^2+h^2+2xh-3x-3h+2-x^2+3x-2$

   $=h^2 + 2xh - 3h$

   $\lim_{h \to 0} \dfrac{h^2+2xh-3h}{h}$

   $= \lim_{h \to 0} h+2x-3$

   $= 2x-3$

** Solution 3

   $f(x) = \dfrac{1}{\sqrt{x}}$

   $f'(x) = \lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}$

   $f(x+h) = \dfrac{1}{\sqrt{x+h}}$

   $f(x) = \dfrac{1}{\sqrt{x}}$

   $f(x+h) - f(x) = \dfrac{1}{\sqrt{x+h}} - \dfrac{1}{\sqrt{x}}$

   $= \dfrac{\sqrt{x}-\sqrt{x+h}}{\sqrt{x+h}\sqrt{x}}$

   $= \dfrac{\sqrt{x}-\sqrt{x+h}}{\sqrt{x+h}\sqrt{x}} * \dfrac{\sqrt{x}+\sqrt{x+h}}{\sqrt{x}+\sqrt{x+h}}$

   $= \dfrac{x-(x+h)}{\sqrt{x+h}\sqrt{x}(\sqrt{x}+\sqrt{x+h})}$

   $= \dfrac{-h}{\sqrt{x+h}\sqrt{x}(\sqrt{x}+\sqrt{x+h})}$

   $\lim_{h \to 0} \dfrac{-1}{\sqrt{x+h}\sqrt{x}(\sqrt{x}+\sqrt{x+h})}$

   $= \dfrac{-1}{\sqrt{x}\sqrt{x}(\sqrt{x} + \sqrt{x})}$

   $= \dfrac{-1}{x(2\sqrt{x})}$

   $= \dfrac{-1}{2x\sqrt{x}}$

** Solution 4

   $g(x) = \sqrt{x^2 + 1}$

   $g'(x) = \lim_{h \to 0} \dfrac{g(x+h)-g(x)}{h}$

   $g(x+h) = \sqrt{(x+h)^2 + 1}$

   $g(x) = \sqrt{x^2 + 1}$

   $g(x+h)-g(x) = \sqrt{(x+h)^2+1} - \sqrt{x^2+1}$

   $= \sqrt{(x+h)^2+1} - \sqrt{x^2+1} * \dfrac{\sqrt{(x+h)^2+1} + \sqrt{x^2+1}}{\sqrt{(x+h)^2+1} + \sqrt{x^2+1}}$

   $= \dfrac{(x+h)^2+1-(x^2+1)}{\sqrt{(x+h)^2+1} + \sqrt{x^2+1}}$

   $= \dfrac{x^2+h^2+2xh+1-x^2-1}{\sqrt{(x+h)^2+1} + \sqrt{x^2+1}}$

   $= \dfrac{h^2+2xh}{\sqrt{(x+h)^2+1} + \sqrt{x^2+1}}$

   $\lim_{h \to 0} \dfrac{h+2x}{\sqrt{(x+h)^2+1} + \sqrt{x^2+1}}$

   $= \dfrac{2x}{\sqrt{x^2+1}+\sqrt{x^2+1}}$

   $= \dfrac{x}{\sqrt{x^2+1}}$

** Solution 5

   $f(x) = 2x-\sqrt{x}$

   $f'(x) = \lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}$

   $f(x+h) = 2(x+h)-\sqrt{x+h} = 2x+2h - \sqrt{x+h}$

   $f(x) = 2x - \sqrt{x}$

   $f(x+h)-f(x) = 2h - \sqrt{x+h} + \sqrt{x}$

   $= 2h + \sqrt{x} - \sqrt{x+h}$

   $= 2h + (\sqrt{x} - \sqrt{x+h} * \dfrac{\sqrt{x}+\sqrt{x+h}}{\sqrt{x}+\sqrt{x+h}})$

   $= 2h + \dfrac{x-(x+h)}{\sqrt{x}+\sqrt{x+h}}$

   $= 2h - \dfrac{h}{\sqrt{x}+\sqrt{x+h}}$

   $\lim_{h \to 0} 2 - \dfrac{1}{\sqrt{x} + \sqrt{x+h}}$

   $= 2 - \dfrac{1}{\sqrt{x} + \sqrt{x}}$

   $= 2 - \dfrac{1}{2\sqrt{x}}$

** Solution 6

   $g(x) = x^3 - 5x$

   $g'(x) = \lim_{h \to 0} \dfrac{g(x+h)-g(x)}{h}$

   $g(x+h) = (x+h)^3-5(x+h)$

   $= (x+h)(x^2+h^2+2xh)-5(x+h)$

   $= (x+h)(x^2+h^2+2xh-5)$

   $g(x+h)-g(x) = xh^2+2x^2h+x^2h + h^3+2xh^2-5h$

   $= xh^2 + 3x^2h + h^3 + 2xh^2 - 5h$

   $\lim_{h \to 0} \dfrac{g(x+h)-g(x)}{h}$

   $= \lim{h \to 0} xh + 3x^2 + h^2 + 2xh - 5$

   $= 0 + 3x^2 + 0 + 0 - 5$

   $= 3x^2 - 5$

** Solution 7

   $f(x) = \sqrt[4]{x}$

   $f'(x) = \lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}$

   $f(x+h) = \sqrt[4]{x+h}$

   $f(x+h)-f(x)= \sqrt[4]{x+h} - \sqrt[4]{x}$

   $(a-b)(a+b) = a^2 - b^2$

   $(a^2 - b^2)(a^2 + b^2) = a^4 - b^4$

   $(a-b)(a+b)(a^2 + b^2) = a^4 - b^4$

   $(a-b)(a^3+ab^2+a^2b + b^3) = a^4 - b^4$

   In our case,

   $a = \sqrt[4]{x+h}$

   $b = \sqrt[4]{x}$

   $\sqrt[4]{x+h} - \sqrt[4]{x} * \dfrac{(\sqrt[4]{x+h})^3 + \sqrt[4]{x+h}(\sqrt[4]{x})^2 + (\sqrt[4]{x+h})^2\sqrt[4]{x} + (\sqrt[4]{x})^3}{(\sqrt[4]{x+h})^3 + \sqrt[4]{x+h}(\sqrt[4]{x})^2 + (\sqrt[4]{x+h})^2\sqrt[4]{x} + (\sqrt[4]{x})^3}$

   $= \dfrac{x+h-x}{(\sqrt[4]{x+h})^3 + \sqrt[4]{x+h}(\sqrt[4]{x})^2 + (\sqrt[4]{x+h})^2\sqrt[4]{x} + (\sqrt[4]{x})^3}$

   $= \dfrac{h}{(\sqrt[4]{x+h})^3 + \sqrt[4]{x+h}(\sqrt[4]{x})^2 + (\sqrt[4]{x+h})^2\sqrt[4]{x} + (\sqrt[4]{x})^3}$

   $\lim_{h \to 0} \dfrac{1}{(\sqrt[4]{x+h})^3 + \sqrt[4]{x+h}(\sqrt[4]{x})^2 + (\sqrt[4]{x+h})^2\sqrt[4]{x} + (\sqrt[4]{x})^3}$

   $= \dfrac{1}{(\sqrt[4]{x})^3 + \sqrt[4]{x}(\sqrt[4]{x})^2 + (\sqrt[4]{x})^2\sqrt[4]{x} + (\sqrt[4]{x})^3}$

   $= \dfrac{1}{3(\sqrt[4]{x})^3}$

** Solution 8

   $g(x) = x^{3/2}$

   $g'(x) = \lim_{h \to 0} \dfrac{g(x+h)-g(x)}{h}$

   $g(x+h) = (x+h)^{3/2}$

   $g(x) = x^{3/2}$

   $g(x+h) - g(x) = (x+h)^{3/2}- x^{3/2}$

   We know that $(a+b)(a-b) = (a^2 - b^2)$

   Putting $a = a^{3/2}$ and $b = b^{3/2}$

   $(a^{3/2} + b^{3/2})(a^{3/2}-b^{3/2}) = a^3 - b^3$

   So, $(x+h)^{3/2} - x^{3/2} = (x+h)^{3/2} - x^{3/2} * \dfrac{(x+h)^{3/2}+x^{3/2}}{(x+h)^{3/2}+x^{3/2}}$

   $= \dfrac{(x+h)^3-x^3}{(x+h)^{3/2}+x^{3/2}}$

   $= \dfrac{h^3 + 3x^2h + 3xh^2}{(x+h)^{3/2}+x^{3/2}}$

   $\lim_{h \to 0} \dfrac{h^2 + 3x^2 + 3xh}{((x+h)^{3/2}+x^{3/2})}$

   $= \dfrac{3x^2}{x^{3/2}+x^{3/2}}$

   $= \dfrac{3x^2}{2x^{3/2}}$

   $= \dfrac{3\sqrt{x}}{2}$

** Solution 9

   $f(x) = \dfrac{3x}{2x+1}$

   $f'(x) = \lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}$

   $f(x+h) = \dfrac{3(x+h)}{2(x+h)+1}$

   $f(x) = \dfrac{3x}{2x+1}$

   $f(x+h) - f(x) = \dfrac{3(x+h)}{2(x+h)+1} - \dfrac{3x}{2x+1}$

   $= \dfrac{3(x+h)(2x+1) - 3x(2(x+h)+1)}{(2x+1)(2(x+h)+1)}$

   $= \dfrac{3(2x^2 + x + 2xh + h) - 3x(2x+2h+1)}{(2x+1)(2(x+h)+1)}$

   $= \dfrac{6x^2 + 3x + 6xh + 3h - 6x^2 - 6hx - 3x}{(2x+1)(2(x+h)+1)}$

   $= \dfrac{3h}{(2x+1)(2(x+h)+1)}$

   $\lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}$

   $= \lim_{h \to 0} \dfrac{3}{(2x+1)(2(x+h)+1)}$

   $= \dfrac{3}{(2x+1)(2x+1)}$

   $= \dfrac{3}{(2x+1)^2}$

** Solution 10

   $\dfrac{d}{dx}((5x+2)^2)$

   $\lim_{h \to 0} \dfrac{(5(x+h)+2)^2 - (5x+2)^2}{h}$

   $(5(x+h)+2)^2 = (5x+5h+2)^2$

   Let $y=5x+2$

   $(y+5h)^2=y^2 + 25h^2 + 106h$

   $(y+5h)^2-y^2=25h^2 + 10yh

   Substituting $y$ back,

   $25h^2 + 10yh = 25h^2 + 10(5x+2)h$

   $= 25h^2 + 10h(5x+2)$

   $\lim_{h \to 0} 25h + 10(5x+2)$

   $= 0 + 10(5x+2)$

   $= 10(5x+2)$

** Solution 11

   $\dfrac{d}{dt} (\dfrac{1}{\sqrt{t}+1})$

   $= \lim_{h \to 0} \dfrac{(\dfrac{1}{\sqrt{t+h}+1}) - (\dfrac{1}{\sqrt{t}+1})}{h}$

   $(\dfrac{1}{\sqrt{t+h}+1}) - (\dfrac{1}{\sqrt{t}+1})$

   $= \dfrac{\sqrt{t}+1-\sqrt{t+h}-1}{(\sqrt{t}+1)(\sqrt{t+h}+1)}$

   $= \dfrac{\sqrt{t}-\sqrt{t+h}}{(t+1)(\sqrt{t+h}+1)} * \dfrac{\sqrt{t} + \sqrt{t+h}}{\sqrt{t} + \sqrt{t+h}}$

   $= \dfrac{-h}{(\sqrt{t}+1)(\sqrt{t+h}+1)(\sqrt{t}+\sqrt{t+h})}$

   $\lim_{h \to 0} \dfrac{-1}{(\sqrt{t}+1)(\sqrt{t+h}+1)(\sqrt{t}+\sqrt{t+h})}$

   $= \dfrac{-1}{(\sqrt{t}+1)(\sqrt{t}+1)(\sqrt{t}+\sqrt{t})}$

   $= \dfrac{-1}{(\sqrt{t}+1)^2(2\sqrt{t})}$

** Solution 12

   $\dfrac{d}{dx}(\dfrac{2z+3}{3z-2})$

   $\lim_{h \to 0} \dfrac{\dfrac{2(z+h)+3}{3(z+h)-2} - \dfrac{2z+3}{3z-2}}{h}$
   
   $\dfrac{2(z+h)+3}{3(z+h)-2} = \dfrac{2z+2h+3}{3z+3h-2}$

   $\dfrac{2z+2h+3}{3z+3h-2} - \dfrac{2z+3}{3z-2}$

   $= \dfrac{(2z+2h+3)(3z-2)-(2z+3)(3z+3h-2)}{(3z+3h-2)(3z-2)}$

   $= \dfrac{(6z^2-4z+6zh-4h+9z-6)-(6z^2+6zh-4z+9z+9h-6)}{(3z+3h-2)(3z-2)}$

   $= \dfrac{-4h-9h}{3z+3h-2}(3z-2)$

   $= \dfrac{-13h}{(3z-2)(3z+3h-2)}$

   $\lim_{h \to 0} \dfrac{-13}{(3z-2)(3z+3h-2)}$

   $= \dfrac{-13}{(3z-2)(3z-2)}$

   $= \dfrac{-13}{(3z-2)^2}$

** Solution 13

   $\dfrac{d}{dx} (\sqrt{x}+3)^2$

   $\lim_{h \to 0} \dfrac{(\sqrt{x+h}+3)^2-(\sqrt{x}+3)^2}{h}$

   $(\sqrt{x+h}+3)^2-(\sqrt{x}+3)^2$

   $= x+h+9+6\sqrt{x+h}-(x+9+6\sqrt{x})$

   $= h+6(\sqrt{x+h}-\sqrt{x})$

   $= h+6(\sqrt{x+h}-\sqrt{x} * \dfrac{\sqrt{x+h}+\sqrt{x}}{\sqrt{x+h}+\sqrt{x}})$

   $= h + 6 (\dfrac{h}{\sqrt{x+h}+\sqrt{x}})$

   $= h(1+ \dfrac{6}{\sqrt{x+h}+\sqrt{x}})$

   $\lim_{h \to 0} 1 + \dfrac{6}{\sqrt{x+h}+\sqrt{x}}$

   $= 1 + \dfrac{6}{\sqrt{x}+\sqrt{x}}$

   $= 1 + \dfrac{3}{\sqrt{x}}$

** Solution 14

   $f(x) = x^2 - 1 ; x \geq 1$

   $f(x) = x - 1 ; x < 1$

   $f'(x) = \lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}$

   $f'(1) = \lim_{h \to 0} \dfrac{f(1+h)-f(1)}{h}$

   $\lim_{h \to 0^-} \dfrac{f(1+h)-f(1)}{h}$

   $\lim_{h \to 0^-} \dfrac{(1+h)-1-(1^2 - 1)}{h}$

   $\lim_{h \to 0^-} \dfrac{h-0}{h} = \lim_{h \to 0} 1 = 1$

   $\lim_{h \to 0^+} \dfrac{f(1+h)-f(1)}{h}$

   $= \lim_{h \to 0^+} \dfrac{(1+h)^2-1-(1^2-1)}{h}$

   $= \lim_{h \to 0^+} \dfrac{(1+h)^2-1}{h}$

   $= \lim_{h \to 0^+} \dfrac{1^2 + h^2 + 2h - 1}{h}$

   $= \lim_{h \to 0^+} h+2 = 2$

   The two sided limit is not same and that means that $f'(1)$ is
   undefined.

** Solution 15

   $g'(x) = \lim_{h \to 0} \dfrac{g(x+h)-g(x)}{h}$

   $g'(1) = \lim_{h \to 0} \dfrac{g(1+h)-g(1)}{h}$

   $\lim_{h \to 0^-} \dfrac{g(1+h)-g(1)}{h}$

   $= \lim_{h \to 0^-} \dfrac{(1+h-1)-(1^2-1)}{h}$

   $= \lim_{h \to 0^-} \dfrac{h}{h} = 1$

   $\lim_{h \to 0^+} \dfrac{g(1+h)-g(1)}{h}$

   $= \lim_{h \to 0^+} \dfrac{(1+h)^2 - (1+h)-(1^2-1)}{h}$

   $= \lim_{h \to 0^+} \dfrac{1^2+h^2+2h-(1+h)}{h}$

   $= \lim_{h \to 0^+} \dfrac{h^2 + 2h - h}{h}$

   $= \lim_{h \to 0^+} h + 1$

   $= 1$

   Hence the derivative exists.

** Solution 16

   $f(x) = \sqrt{|x|}$

   $f'(x) = \lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}$

   Let's compute $f'(0)$

   $\lim_{h \to 0^-} \dfrac{f(x+h)-f(x)}{h}$

   $= \lim_{h \to 0^-} \dfrac{\sqrt{|h|}-\sqrt{|0|}}{h}$

   $= \lim_{h \to 0^-} \dfrac{\sqrt{h}}{h}$

   $= \lim_{h \to 0^-} \dfrac{1}{\sqrt{h}}$
   
   $\lim_{h \to 0^+} \dfrac{f(x+h)-f(x)}{h}$

   $= \lim_{h \to 0^+} \dfrac{\sqrt{|h|}-\sqrt{|0|}}{h}$

   $= \lim_{h \to 0^+} \dfrac{\sqrt{h}}{h}$

   $= \lim_{h \to 0^+} \dfrac{1}{\sqrt{h}}$

   Even though In both the cases, the limit is undefined. Hence the
   derivative does not exist.

** Solution 17

   $g(x) = |x|^{3/2} = |x|\sqrt{|x|}$

   $g'(x) = \lim_{h \to 0} \dfrac{g(x+h)-g(x)}{h}$

   Let's compute $g'(0)$

   $\lim_{h \to 0^-} \dfrac{g(0+h)-g(0)}{h}$

   $= \lim_{h \to 0^-} \dfrac{|0+h|\sqrt{|0+h|}-0}{h}$

   $= \lim_{h \to 0^-} \sqrt{h} = 0$

   $\lim_{h \to 0^+} \dfrac{g(0+h)-g(0)}{h}$

   $= \lim_{h \to 0^+} \dfrac{|0+h|\sqrt{|0+h|}-0}{h}$

   $= \lim_{h \to 0^+} \dfrac{|h|\sqrt{|h|}}{h}$

   $= \lim_{h \to 0^+} \sqrt{h} = 0$

   The two sided limit is defined and the domain exists so the
   derivative exists.
