* Sophisticated Graphing

** General procedure for graphing

These are the the general steps while you try to compute the graph of
a function $f$:

1. Determine domain of the $f$
2. Find $f'(x)$ and use it to determine intervals on which $f$ is
  increasing or decreasing, and local maximum or minimum points.
3. Find $f''(x)$ and use it to determine intervals on which $f$ is
  [[file:section4.org][concave up or down, and inflection points.]]
4. Use limits to find all vertical and horizontal asymptotes.
5. Plot important points and sketch the curve!

Notes:

- If $f(x)$ is undefined at some point, investigate what happens when
  $x$ approaches the point from it's left and right side.
- If the limit of the above computation is infinity (with different
  signs) on different directions, they you have a vertical asymptotes.
- To check for horizontal asymptote, you can compute the limit of the
  function with $x \to \infty$ and $x \to -\infty$ and see if they
  give the same value.
- [[https://en.wikipedia.org/wiki/Asymptote#Asymptotes_of_functions][Wikipedia link for computing horizontal/vertical asymptotes]]

** Theorem 4.5.5

Suppose $f$ is a function whose domains contains an interval $(a,
\infty)$, and let $A$ be the set of all the values of $f$ at numbers
in this interval; that is, $A = { f(x): x > a} = {y: \text{for some } x > a, y
= f(x)}$.

1. If $f$ is weakly increasing on $(a, \infty)$ and $A$ has an upper
   bound, then $\lim_{x \to \infty} f(x)$ is defined and is equal to
   the least upper bound of $A$.
2. If $f$ is weakly increasing on $(a, \infty)$ and $A$ does not have
   an upper bound, then $\lim_{x \to \infty} f(x) = \infty$
3. If $f$ is weakly decreasing on $(a, \infty)$ and $A$ has a lower
   bound, then $\lim_{x \to \infty} f(x)$ is defined and is equal to
   the greatest lower bound of $A$.
4. If $f$ is weakly decreasing on $(a, \infty)$ and $A$ does not have
   a lower bound, then $\lim_{x \to \infty} f(x) = -\infty$
