* Related Rates

** Solution 1

$P$ = Power measured in watts

$I$ = Current in amperes.

$P = 25 I^2$

At $t = t_1$,

$I = 4$ amperes

$\dfrac{dI}{dt} = 2$  amps/ min

$\dfrac{dP}{dt} = ?$

$P = 25I^2$

$\dfrac{dP}{dt} = 50 * \dfrac{dI}{dt}$

$= 50 I \dfrac{dI}{dt}$

At $t_1$,

$\dfrac{dP}{dt} = 50 * 4 *  2 = 400$  W/min

The power is increasing 400 W/min.

** Solution 2

$V =$ Volume of gas in cyclinder in cubic inches

$P =$ Pressure of gas in kilopascals

$P = \dfrac{3000}{V}$

At $t = t_1$,

$V = 20$ cubic inches.

$\dfrac{dV}{dt} = 3$  $in^3/sec$

$\dfrac{dP}{dt} = ?$

$P = \dfrac{3000}{V}$

$P = 3000 V^{-1}$

$\dfrac{dP}{dt} = 3000 * (-1)V^{-2} \dfrac{dV}{dt}$

$\dfrac{dP}{dt} = 3000 * -1 * (20)^-2 * 3$

$= \dfrac{-3000}{20^2} * 3 = -22.5$ kp/sec.

The pressure is decreasing 22.5 kp/sec.

** Solution 3

V = Volume of spherical bulb in inches.

r = radius of the baloon in inches.

$\forall t. \dfrac{dv}{dt} = 5$ in^3/s

At $t = t_1$,

$r = 3$

$\dfrac{dr}{dt} = ?$

$V = \dfrac{4}{3}\pi r^3$

$\dfrac{dV}{dt} = \dfrac{4}{3} \pi 3r^2 \dfrac{dr}{dt} = 4\pi r^2 \dfrac{dr}{dt}$

At $t_1$,

$\dfrac{dV}{dt} = 4\pi r^2 \dfrac{dr}{dt}$

$5 = 4\pi (3^2) \dfrac{dr}{dt}$

$\dfrac{dr}{dt} = \dfrac{5}{4\pi 3^2} = \dfrac{5}{36 \pi}$ in/s

** Solution 4

todo: insert pic

x = Length of Alice's shardow in feet

y = Distance between Alice and street light

We need to prove $\dfrac{dx}{dt}$ is constant.

$\dfrac{dy}{dt} = 2 ft/s$

Using the property of similar triangle,

$\dfrac{9}{y + x} = \dfrac{5}{x}$

$9x = 5y + 5x$

$4x = 5y$

$4 \dfrac{dx}{dt} = 5 \dfrac{dy}{dt}$

$\dfrac{dx}{dt} = \dfrac{5dy}{4dt} = \dfrac{5}{4} * 2 = 2.5$ ft/s

So, $\dfrac{dx}{dt}$ is constant and it is getting longer as $2.5 >
2$.

** Solution 5

todo: insert pic

x = Alice's height in feets

$\dfrac{dx}{dt} = -2f/min$

y = Alice's shadow in feets

$\dfrac{dy}{dt} = ?$

Using the property of similar triangle,

$\dfrac{9}{8 + y} = \dfrac{x}{y}$

$9y = 8x + xy$

$9\dfrac{dy}{dt} = 8\dfrac{dx}{dt} + x\dfrac{dy}{dt} + y \dfrac{dx}{dt}$

$\dfrac{dy}{dt}(9-x) = \dfrac{dx}{dx}(8+y)$

At $x=3$ feet,

$\dfrac{dy}{dt}(9-x) = \dfrac{dx}{dt}(8+y)$

$\dfrac{dy}{dt} * 6 = -2 (8+y)$

$\dfrac{dx}{dt} = -\dfrac{8+y}{3}$

We already know that

$\dfrac{9}{8+y} = \dfrac{x}{y} = \dfrac{3}{y}$

$9y = 24 + 3y$

$6y = 24$

$y = 4$

$\dfrac{dx}{dt} = \dfrac{-(8+y)}{3} = \dfrac{-12}{3} = -4$ ft/min

The shadow is decreasing 4 feet per min.

** Solution 6

todo: insert pic

x = distance between building and car in feets

y = distance between the road and the car in feets

We need to find $\dfrac{dx}{dt}$ when $y = 100$

$x^2 = 50^2 + y^2$

$2x\dfrac{dx}{dt} = 2y \dfrac{dy}{dt}$

$\dfrac{dx}{dt} = \dfrac{y}{x} * \dfrac{dy}{dt}$

$\dfrac{dy}{dt} = 30 ft/sec$

$\dfrac{dx}{dt} = \dfrac{y}{x} \dfrac{dy}{dt}$

We know that

$x^2 = 50^2 + y^2$

$x^2 = 50^2 + 100^2 = 2500 + 10000$

$x^2 = 12500$

$\dfrac{dx}{dt} = \dfrac{100}{12500} \dfrac{dy}{dt} = \dfrac{1}{125} * 30 = 30/125$

$\dfrac{dx}{dt} \approx 0.24$ ft/s

** Solution 7

todo: insert pic

x = Distance between the bottom of the ladder and the wall in feets.

y = Distance between the top of the ladder and the wall in feets.

Length of ladder = 15 feet

$\dfrac{dx}{dt} = 2 $ ft/s

At $y = 12$ feet, $\dfrac{dy}{dt} = ?$

$15^2 = x^2 + y^2$

$0 = 2x \dfrac{dx}{dt} + 2y \dfrac{dy}{dt}$

$15^2 = x^2 + 12^2$

$x^2 = 15^2 - 12^2 = 81$

$x = 9$

$2x \dfrac{dx}{dt} + 2y \dfrac{dy}{dt} = 0$

$2*9*2 + 2*12*\dfrac{dy}{dt} = 0$

$\dfrac{dy}{dt} = \dfrac{-2*9*2}{2*12} = \dfrac{-2*9}{12} = \dfrac{-3}{2} = -1.5$ ft/s

The top of the ladder is sliding down at $1.5$ feet per second.

** Solution 8

todo: insert pic

Bottom of the ladder is fixed.

y = Distance between the top of the ladder and the wall in feets.

x = Distance between the ladder.

$\dfrac{dx}{dt} = 2$ ft/s

At $x = 5$ feet, $\dfrac{dy}{dt} = ?$

$x^2 = 3^2 + y^2$

$5^2 = 3^2 + y^2$

$y^2 = 5^2 - 3^2 = 16$

$y = 4$

$x^2 = 3^2 + y^2$

$2x \dfrac{dx}{dt} = 2y\dfrac{dy}{dt}$

$2*5*2 = 2*4* \dfrac{dy}{dt}$

$\dfrac{dy}{dt} = \dfrac{2*5*2}{2*4} = \dfrac{5}{2} = 2.5$ ft/s

The ladder is sliding up the wall at $2.5$ ft/s when the ladder is 5
feet long.

** Solution 9

todo: insert pic

x = Distance between the rocket and ground in km.

$\theta$ = Anble between the camera and rocket when focused.

When $x=1$ km, $\dfrac{d\theta}{dt} = 0.1$ rad/sec

$\dfrac{dx}{dt} = ?$

$\tan \theta = \dfrac{x}{x}$

$\sec^2 \theta \dfrac{d\theta}{dt} = \dfrac{dx}{dt} * \dfrac{1}{2}$

y = Distance between the camera and the top of the rocket.

$y^2 = 2^2 + 1^2 = 5$

$y = \sqrt{5}$

$\cos \theta = \dfrac{2}{\sqrt{5}}$

$\cos^2 \theta = \dfrac{4}{5}$

$\sec^2 \theta = \dfrac{5}{4}$

$\sec^2 \theta \dfrac{d\theta}{dt} = \dfrac{dx}{dt} * \dfrac{1}{2}$

$\dfrac{5}{4} * 0.1 = \dfrac{1}{2} \dfrac{dx}{dt}$

$\dfrac{5}{4} * 0.1 = \dfrac{1}{2} \dfrac{dx}{dt}$

$\dfrac{5}{4} * 0.1 = \dfrac{1}{2} \dfrac{dx}{dt}$

$\dfrac{dx}{dt} = \dfrac{0.5}{4} * 2 = \dfrac{0.5}{2} = \dfrac{5}{20} = \dfrac{1}{4}$

$= 0.25$ km/s

** Solution 10

todo: insert pic

$\theta =$ Angle between the police and car in radians.

x = Distance between car and the shortedst distance between road and
police.

At $\theta = \dfrac{\pi}{3}$, $\dfrac{d\theta}{dt} = \dfrac{1}{20}$ rad/s

Speed limit of road = 65mph

Since sum of angle inside the triangle is 180,

$\dfrac{\pi}{3} + \dfrac{\pi}{2} + a = 180$

$\dfrac{2\pi + 3\pi}{6} + a = 2\pi$

$a = 2\pi - \dfrac{5\pi}{6} = \dfrac{12\pi}{6} - \dfrac{5\pi}{6}$

$a = \dfrac{7\pi}{6}$

$\tan \dfrac{7\pi}{6} = \dfrac{1/10}{x} = \dfrac{1}{10x}$

$x = \dfrac{1}{10 \tan (7\pi/6)} = \dfrac{\sqrt{3}}{10}$

We know that,

$\tan(\pi - \dfrac{\pi}{2} - \theta) = \dfrac{1/10}{x}$

$\tan (\dfrac{\pi}{2} - \theta) = \dfrac{1}{10x}$

$\cot \theta = \dfrac{1}{10x}$

$\cot \theta = \dfrac{1}{10}x^{-1}$

$-\csc^2 \theta \dfrac{d\theta}{dt} = -\dfrac{1}{10}x^{-2}\dfrac{dx}{dt}$

$-\csc^2 \theta \dfrac{d\theta}{dt} = -\dfrac{1}{10} (\dfrac{\sqrt{3}}{10})^{-2}\dfrac{dx}{dt}$

$-(\dfrac{2}{\sqrt{3}})^2 \dfrac{1}{20} = -\dfrac{1}{10} (\dfrac{10}{\sqrt{3}})^{2}\dfrac{dx}{dt}$

$-\dfrac{4}{3} \dfrac{1}{20} = -\dfrac{1}{10} * \dfrac{10^2}{3} \dfrac{dx}{dt}$

$-\dfrac{1}{15} = \dfrac{-10}{3} \dfrac{dx}{dt}$

$\dfrac{dx}{dt} = \dfrac{1}{5*10} = \dfrac{1}{50}$ m/s

$= \dfrac{1}{50} * 3600$ m/h

$= 72$ m/h

So, yes the driver should be given a speeding ticket!

** Solution 11

V = Volume of sand in the cone measured in $ft^3$

h = height of the sand pile

r = Radius of the base

$\dfrac{dr}{dt} = 2$ ft^3/sec

$h = r$

At $h = 5$, $\dfrac{dh}{dt} = ?$

$V = \dfrac{1}{3}\pi r^2 h = \dfrac{1}{3} \pi h^3$

$\dfrac{dV}{dt} = \dfrac{3h^2}{3} \pi \dfrac{dh}{dt} = h^2 \pi \dfrac{dh}{dt}$

$2 = 5^2 \pi \dfrac{dh}{dt}$

$\dfrac{dh}{dt} = \dfrac{2}{5^2 \pi} = 0.025$ feet/sec

** Solution 12

todo: insert pic

y = Distance between traffic intersection and the van.

x = Distance between traffic intersection and the police car.

At $t = t_1$,

At $x = 2$ miles,

$\dfrac{dx}{dt} = 80$ mph

$y = 3$ miles

$\dfrac{dy}{dt} = 60$ mph

z = Distance between the van and the police vehicle.

$z^2 = x^2 + y^2$

We need to find $\dfrac{dz}{dt}$ at $t = t_1$

$2z \dfrac{dz}{dt} = 2x\dfrac{dx}{dt} + 2y\dfrac{dy}{dt}$

$z^2 = 2^2 + 3^2 = 13$

$z = \sqrt{13}$

$2\sqrt{13} \dfrac{dz}{dt} = 2*2*80 + 2*3*60$

$\dfrac{dz}{dt} = \dfrac{680}{2\sqrt{13}} = 94.29$ mph


