* Antiderivatives

** Solution 1

$f(x) = 2x^3 - 9x^2 + 3x - 1$

Domain: $(-\infty, \infty)$

Let's solve this using GNU Octave:

#+begin_src octave :session :eval never-export :results value verbatim output :exports both
clear
pkg load symbolic
syms x
f = 2*x^3 - 9*x^2 + (3*x) - 1
#+end_src

#+RESULTS:
:
: octave> octave> f = (sym)
:
:      3      2
:   2⋅x  - 9⋅x  + 3⋅x - 1

#+begin_src octave :session :eval never-export :results value verbatim output :exports both
int(f, x)
#+end_src

#+RESULTS:
: ans = (sym)
:
:    4             2
:   x       3   3⋅x
:   ── - 3⋅x  + ──── - x
:   2            2


So the antiderivative is $\dfrac{x^4}{2} - 3*x^3 + \dfrac{3x^2}{2} -
2$ on the interval $(-\infty, \infty)$.

** Solution 2

$g(x) = \sqrt{x} + \sqrt[3]{x}$

Domain: $(0, \infty)$

Let's solve this using GNU Octave:

#+begin_src octave :session :eval never-export :results value verbatim output :exports both
clear
pkg load symbolic
syms x
g = sqrt(x) + (x)^(1/3)
#+end_src

#+RESULTS:
#+begin_example

octave> octave> warning: passing floating-point values to sym is dangerous, see "help sym"
warning: called from
    double_to_sym_heuristic at line 50 column 7
    sym at line 379 column 13
    mpower at line 76 column 5
g = (sym)

  3 ___
  ╲╱ x  + √x
#+end_example

#+begin_src octave :session :eval never-export :results value verbatim output :exports both
int(g,x)
#+end_src

#+RESULTS:
: ans = (sym)
:
:      4/3      3/2
:   3⋅x      2⋅x
:   ────── + ──────
:     4        3

Intervals where the antiderivaties apply is same as the original
function's domain.

** Solution 3

$f(x) = \sin x + \cos x$

Domain: $(-\infty, \infty)$

Let's solve this using GNU Octave:

#+begin_src octave :session :eval never-export :results value verbatim output :exports both
clear
pkg load symbolic
syms x
f = sin(x) + cos(x)
int(f,x)
#+end_src

#+RESULTS:
:
: octave> octave> f = (sym) sin(x) + cos(x)
: ans = (sym) sin(x) - cos(x)

Intervals where the antiderivaties apply is same as the original
function's domain.

** Solution 4

$g(x) = \sec x(\sec x + \tan x)$

Let's find the domain of the above function.

We know than $\sec x = \dfrac{1}{\cos x}$ and $\tan x = \dfrac{\sin x}{\cos x}$

So, $g(x) = \sec^2 x + \sin x \sec^2 x$

We know the domain of $\sin x$ is $(-\infty, \infty)$. But domain of
$\sec x$ is $R - \dfrac{\pi}{2} - n*\pi$

So the domain of the function $g(x)$ is $R - \dfrac{\pi}{2} - n*\pi$.

Let's solve this using GNU Octave:

#+begin_src octave :session :eval never-export :results value verbatim output :exports both
clear
pkg load symbolic
syms x
g = sec(x)*(sec(x) + tan(x))
int(g,x)
#+end_src

#+RESULTS:
:
: octave> octave> g = (sym) (tan(x) + sec(x))⋅sec(x)
: ans = (sym) tan(x) + sec(x)

Intervals where the antiderivaties apply is same as the original
function's domain.
