* Definite Integrals

** Definition 5.3.1

Suppose that $a < b$, $f$ is a function that is defined on the closed
interval $[a,b]$, and $n$ is a positive integer. Let $\Delta x =
\dfrac{b-a}{n}$, and for $0 \leq i \leq n$ let $x_i = a + i\Delta
x$. These numbers divide the interval $[a,b]$ into $n$ smaller
intervals $[x_0, x_1], [x_1, x_1], ..., [x_{n-1}, x_n]$, each of width
$\Delta x$. Also, suppose that for $1 \leq i \leq n, x^{*}_i \in
[x_{i-1}, x_i]$. Then the sum

$f(x^{*}_1)\Delta x + f(x^{*}_2)\Delta x + ... + f(x^{*}_n)\Delta x = \sum_{i=1}^nf(x^{*}_i)\Delta x$

is called a *Riemann sum* for $f$ on the interval $[a,b]$. We may also
call it a *Riemann n-sum* if weant to specify the number of terms in
the sum.

** Theorem 5.3.2

Suppose that $a < b$ and $f$ is a function that is continous on the
closed interval $[a,b]$. Then every Riemann sum sequence for $f$ on
$[a,b]$ converges, and all such sequece converge to the same
number. In other words, there is some number $L$ such that if
$(R_n)^{\infty}_{n=1}$ is any Riemann sum sequence for $f$ on $[a,b]$,
then $\lim_{n \to \infty} R_n = L$.

** Definition 5.3.3

Suppose that $a < b$ and $f$ is continous on $[a,b]$. Then the number
$L$ that is the limit of all Riemann sum sequences for $f$ on $[a,b]$
is called the *definite integral* of $f$ from $a$ to $b$, and it is
denoted $\int_a^b f(x) \mathrm{d} x$. In other words, for any Riemann
sum sequence $(R_n)^{\infty}_{n=1}$,

$\int_a^b f(x) \mathrm{d} x = \lim_{n \to \infty} R_n$

- The number $a$ is called the *lower limit of integration* (Not to be
  confused with the standard meaning of limit)
- The number $b$ is called the *upper limit of integration*
- $f(x)$ is called the *integrand*

More informally, in the notation of Definition 5.3.1 we can say that
for large $n$,

$\int_a^b f(x) \mathrm{d} x \approx \sum_{i=1}^n f(x_i^{*})\Delta x$

- The symbol $\int$ is called an *integral sign*. It is an elongated
  $S$ which is intended to remind you that the expression on the right
  is a sum.
- The expression $f(x) \mathrm{d}x$ on the left is supposed to remind
  you of the formula $f(x_i^{*})\Delta x$ that appears in the Riemann
  sum on the right.
- The *$\mathrm{d}x$* at the end of the integral notation is to
  identify the independent variable. (They also play an imporant role
  in the method of integration by substitution)
- Geometrical interpretation:
  - If $f(x)$ is positive for all values of $x$, then $\int_a^b f(x)
    \mathrm{d}x$ is equal to the area of the region under the graph of
    $f$ for $a \leq x \leq b$
  - If $f(x)$ is not always positive, then we divide the region
    between the graph of $f$ and the $x$ axis for $a \leq x \leq b$
    into two parts, the part above the x-axis and the part below. The
    value of $\int_a^b f(x) \mathrm{d}x$ is equal to the area of the
    part above the x-axis minus the area of the part below.
