* Summations

** Solution 1

*** Solution a

[[https://psibi.in/velleman-calculus/chapter5/section1.html#sec-1-2][From theorem 5.1.1]], we can rewrite them as individual summations:

#+begin_src sage :exports both
i, n = var('i,n')
a = sum(i^2, i , 1, n)
a

b = sum(-2*i, i, 1, n)
b

c = sum(3, i, 1, n)
c

d = a + b + c
d
d.factor()
#+end_src

#+RESULTS:
: 1/3*n^3 + 1/2*n^2 + 1/6*n
: -n^2 - n
: 3*n
: 1/3*n^3 - 1/2*n^2 + 13/6*n
: 1/6*(2*n^2 - 3*n + 13)*n

We can indeed confirm the result:

#+begin_src sage :exports both
i,n = var('i n')
f = i^2 - (2*i) + 3
sum(f(i), i, 1, n).factor()
#+end_src

#+RESULTS:
: 1/6*(2*n^2 - 3*n + 13)*n

*** Solution b

#+begin_src sage :exports both
sum((i^2 - (2*i) + 3), i, 1, 5)
#+end_src

#+RESULTS:
: 40

#+begin_src sage :exports both
f
f(1) + f(2) + f(3) + f(4) + f(5)
#+end_src

#+RESULTS:
: i^2 - 2*i + 3
: 40

** Solution 2

From theorem 5.1.1 and results from 1.4, we can rewrite them as
individual summations:

#+begin_src sage :exports both
i, n = var('i n')
f = i^3 - (4*i)

a = sum(i^3, i, 1, n).factor()
b = sum((-4*i),i,1,n).factor()

(a + b).factor()
#+end_src

#+RESULTS:
: 1/4*(n^2 + n - 8)*(n + 1)*n

Let's check our solution:

#+begin_src sage :exports both
sum(f,i,1,n).factor()
#+end_src

#+RESULTS:
: 1/4*(n^2 + n - 8)*(n + 1)*n

** Solution 3

From theorem 5.1.1 and results from 1.4, we can rewrite them as
individual summations:

#+begin_src sage :exports both
j, n = var('j n')

a = sum(2*(j^3), j, 1, n)
b = sum(-1*j, j, 1, n)

(a - b).factor()
#+end_src

#+RESULTS:
: 1/2*(n^2 + n + 1)*(n + 1)*n

** Solution 4

From theorem 5.1.1 and results from 1.4, we can rewrite them as
individual summations:

#+begin_src sage :exports both
i, t = var('i t')

a = sum(3 * (i^2), i, 1, t)
b = sum(-i, i, 1, t)
c = sum(2, i, 1, t)

(a + b + c).factor()
#+end_src

#+RESULTS:
: (t^2 + t + 2)*t

Let's verify the solution:

#+begin_src sage :exports both
f = 3*(i^2) - i + 2
sum(f(i), i, 1, n).factor()
#+end_src

#+RESULTS:
: (n^2 + n + 2)*n

** Solution 5

Let's expand $(1+1)^3$:

#+begin_src sage :exports both
i = var('i')
((i+1)^3).expand()
#+end_src

#+RESULTS:
: i^3 + 3*i^2 + 3*i + 1

Now from theorem 5.1.1 and results from 1.4, we can rewrite them as
individual summations:

#+begin_src sage :exports both
i = var(i)

a = sum(i^3, i, 1, n)
b = sum(3*(i^2), i, 1, n)
c = sum(3*i, i, 1, n)
d = sum(1, i, 1, n)

(a+b+c+d).factor()
#+end_src

#+RESULTS:
: 1/4*(n^2 + 3*n + 4)*(n + 3)*n

** Solution 6

Let's find the solution from $i = 1$ to $i = n+3$ in this case:

#+begin_src sage :exports both
i, n = var('i n')
whole = sum(i^2, i, 1, n+3).factor()
whole
#+end_src

#+RESULTS:
: 1/6*(2*n + 7)*(n + 4)*(n + 3)

Now let's compute the summation from $i = 1$ to $i = 4$:

#+begin_src sage :exports both
till_4 = sum(i^2, i, 1, 4)
till_4
#+end_src

#+RESULTS:
: 30

The final solution is:

#+begin_src sage :exports both
(whole - till_4).factor()
#+end_src

#+RESULTS:
: 1/6*(2*n^2 + 23*n + 96)*(n - 1)

Let's verify the solution:

#+begin_src sage :exports both
i, n = var('i n')
sum(i^2, i, 5, (n+3)).factor()
#+end_src

#+RESULTS:
: 1/6*(2*n^2 + 23*n + 96)*(n - 1)

** Solution 7

*** Solution a

Now from theorem 5.1.1 and results from 1.4, we can rewrite them as
individual summations:

#+begin_src sage :exports both
i, n = var('i n')

a = sum(i^2, i, 1, n)
b = sum(5*i, i, 1, n)
(a+b).factor()
#+end_src

#+RESULTS:
: 1/3*(n + 8)*(n + 1)*n

*** Solution b

Now from theorem 5.1.1 and results from 1.4, we can rewrite them as
individual summations. Let's find the sum from $j = 1$ to $n+5$

#+begin_src sage :exports both
j, n = var('j n')

a = sum(j^2, j, 1, n+5)
b = sum(-5*j, j, 1, n+5)
(a + b).factor()
#+end_src

#+RESULTS:
: 1/3*(n + 6)*(n + 5)*(n - 2)

Now let's compute the same sum from $j = 1$ to $5$:

#+begin_src sage :exports both
a1 = sum(j^2, j, 1, 5)
b1 = sum(-5*j, j, 1, 5)
(a + b - a1 - b1).factor()
#+end_src

#+RESULTS:
: 1/3*(n + 8)*(n + 1)*n

*** Solution c

We have already shown from (a) and (b) that they are equal. Let's
expand them:

#+begin_src sage :exports both
i = var(i)
f = i^2 + 5*i
[f(1) , f(2) , f(3) , f(n).factor()]

g = j^2 - 5*j
[g(6), g(7), g(8), g(n+6).factor()]
#+end_src

#+RESULTS:
: [6, 14, 24, (n + 5)*n]
: [6, 14, 24, (n + 6)*(n + 1)]

We can see how each of them expand to the same value when started from
their staring interval. That's why both come to the same value:

#+begin_src sage :exports both
f(n).factor()
g(n+5).factor()
#+end_src

#+RESULTS:
: (n + 5)*n
: (n + 5)*n

** Solution 8

*** Part one

We need to prove this:

$\sum_{i=1}^n (ca_i) = ca_1 + ca_2 + ... + ca_n = c(a_1 + a_2 + ... + a_n) = c\sum_{i=1}^n a_i$

We will prove using mathematical induction.

Base case: $n= 1$

$\sum_{i=1}^n ca_i = ca_1$

Induction step: Suppose $\sum_{i=1}^n (ca_i) = c\sum_{i=1}^n a_i$

$\sum_{i=1}^{n+1} (ca_i) = \sum_{i=1}^n (ca_i) + ca_{n+1}$

$= c\sum_{i=1}^n a_i + ca_{n+1}$ (Induction case)

$= c(\sum_{i=1}^n a_i + a_{n+1})$

$= c(\sum_{i=1}^{n+1} a_i)$

This completes the mathematical induction proof.

*** Part two

We need to prove this:

$\sum_{i=1}^n (a_i + b_i) = \sum_{i=1}^n a_i + \sum_{i=1}^n b_i$

We will prove using mathematical induction.

Base case: $n = 1$

$\sum_{i=1}^n (a_i + b_i) = a_i + b_i$

Induction step: Suppose $\sum_{i=1}^n (a_i + b_i) = \sum_{i=1}^n a_i +
\sum_{i=1}^n b_i$

$\sum_{i=1}^{n+1} (a_i + b_i)$

$= \sum_{i=1}^{n} (a_i + b_i) + a_{n+1} + b_{n+1}$

$= \sum_{i=1}^n a_i + \sum_{i=1}^n b_i + a_{n+1} + b_{n+1}$

$= \sum_{i=1}^n a_{i+1} + \sum_{i=1}^n b_{i+1}$

$= \sum_{i=1}^{n+1} a_{i} + \sum_{i=1}^{n+1} b_{i}$

This completes the mathematical induction proof.

** Solution 9

$\sum_{i=1}^n [(i+1)^4 - i^4]$

We need to derive equation 5.9 using the above equation.

Let's first expand the above equation:

#+begin_src sage :exports both
  i = var('i')
  f1 = (i+1)^4
  f2 = -i^4
  [f1(1), f2(1), f1(2), f2(2), f1(3), f2(3), f1(4), f2(4), f1(i-1), f2(i-1), f1(i), f2(i)]
#+end_src

#+RESULTS:
: [16, -1, 81, -16, 256, -81, 625, -256, i^4, -(i - 1)^4, (i + 1)^4, -i^4]

You can see that the first term is cancelled by the fourth term. The
third term is cancelled by two terms following it. So apart from $-1$
and $(i+1)^4$ everything else is cancelled.

So, $\sum_{i=1}^n [(i+1)^4 - i^4] = (i+1)^4 - 1$

We also know that:

#+begin_src sage :exports both
x = (i+1)^4 - i^4
x.simplify_full()
#+end_src

#+RESULTS:
: 4*i^3 + 6*i^2 + 4*i + 1

So, $\sum_{i=1}^n [(i+1)^4 - i^4] = \sum_{i=1}^n(4*i^3 + 6*i^2 + 4i + 1)$

Combining both the equations:

$(i+1)^4 - 1 = 4. \sum_{i=1}^n i^3 + \sum{i=1}^n(6*i^2 + 4*i + 1)$

#+begin_src sage :exports both
sum(((6*i^2) + (4*i) + 1), i, 1, n)
#+end_src

#+RESULTS:
: 2*n^3 + 5*n^2 + 4*n

Reducing it further:

$(n+1)^4 - 1 = 4. \sum_{i=1}^n i^3 + 2*n^3 + 5*n^2 + 4n$

$4\sum_{i=1}^n i^3 = (n+1)^4 - 1 - 2*n^3 - 5*n^2 - 4n$

Reducing the equations:

#+begin_src sage :exports both
n = var('n')
((n+1)^4 - 1 - (2*n^3) - (5*n^2) - (4*n)).factor()
#+end_src

#+RESULTS:
: (n + 1)^2*n^2

So, $\sum_{i=1}^n i^3 = \dfrac{n^2(n+1)^2}{4}$

** Solution 10

We need to find alternative derivation of equation 5.4 by evaulating
$\sum_{i=1}^n [(i+1)^2-i^2]$

Let's first expand the equation:

#+begin_src sage :exports both
i = var(i)
f1 = (i+1)^2
f2 = -i^2

[f1(1), f2(1), f1(2), f2(2), f1(3), f2(3), f1(i-1), f2(i-1), f1(i), f2(i)]
#+end_src

#+RESULTS:
: [4, -1, 9, -4, 16, -9, i^2, -(i - 1)^2, (i + 1)^2, -i^2]

Apart from $-1$ and $(i+1)^2$ everything else gets cancelled out.

So, $\sum_{i=1}^n [(i+1)^2-i^2] = (n+1)^2 - 1$

We also know that:

#+begin_src sage :exports both
((i+1)^2 - i^2).simplify_full()
#+end_src

#+RESULTS:
: 2*i + 1

So, $\sum_{i=1}^n [(i+1)^2-i^2] = \sum_{i=1}^n 2i + 1$

Combining both the equations:

$(n+1)^2 - 1 = \sum_{i=1}^n 2i + 1$

$\sum_{i=1}^n i = \dfrac{(n+1)^2 - n}{2}$

#+begin_src sage :exports both
((n+1)^2 - n - 1).simplify_full()
#+end_src

#+RESULTS:
: n^2 + n

So, $\sum_{i=1}^n i = \dfrac{n^2 + n}{2}$

** Solution 11

We need to prove $\sum_{i=1}^n i = \dfrac{n^2 + n}{2}$

We will prove using mathematical induction.

Base case: $n = 1$

$\sum_{i=1}^n i = \dfrac{1 + 1}{2} = \dfrac{1}{1} = 1$

$\sum_{i=1}^1 = 1$

The base case holds.

Induction step: Suppose $\sum_{i=1}^n i = \dfrac{n^2 + n}{2}$.

$\sum_{i=1}^{n+1} i = \sum_{i=1}^n i + (n+1)$

$\sum_{i=1}^{n+1} i = \dfrac{n^2 + n}{2} + (n+1)$ (Induction step)

#+begin_src sage :exports both
(((n^2 + n)/2) + (n+1)).factor()
#+end_src

#+RESULTS:
: 1/2*(n + 2)*(n + 1)

#+begin_src sage :exports both
((n+1)*(n+2)).simplify_full()
#+end_src

#+RESULTS:
: n^2 + 3*n + 2

So, $\sum_{i=1}^{n+1} i = \dfrac{(n+1)^2 + (1+n)}{2}$

This completes the mathematical induction proof.

** Solution 12

*** Solution a

$\sum_{i=1}^n \dfrac{1}{i(i+1)}$

#+begin_src sage :exports both
i, n = var('i n')
f = (1/(i*(i+1)))
[sum(f(i), i, 1, 1), sum(f(i), i, 1, 2), sum(f(i), i, 1, 3), sum(f(i), i, 1, 4)]
#+end_src

#+RESULTS:
: [1/2, 2/3, 3/4, 4/5]

So, I'm guessing the formula for the sum as:

$\dfrac{n}{n+1}$

Let's try to prove it using mathematical induction.

Base case: $n = 1$

$\sum_{i=1}^n \dfrac{1}{i(i+1)} = \dfrac{1}{1(1+1)} = \dfrac{1}{2}$

$\dfrac{n}{n+1} = \dfrac{1}{2}$

The base case holds.

Induction step: Suppose $\sum_{i=1}^n \dfrac{1}{i(i+1)} = \dfrac{n}{n+1}$

$\sum_{i=1}^{n+1} \dfrac{1}{i(i+1)} = \sum_{i=1}^n \dfrac{1}{i(i+1)} + \dfrac{1}{(n+1)(n+2)}$

$= \dfrac{n}{n+1} + \dfrac{1}{(n+1)(n+2)}$ (Induction step)

$= \dfrac{1}{n+1}(n + \dfrac{1}{n+2})$

$= \dfrac{1}{n+1} \dfrac{n^2 + 2n + 1}{n+2}$

$= \dfrac{1}{n+1} \dfrac{(n+1)^2}{n+2}$

$= \dfrac{n+1}{n+2}$

So, $\sum_{i=1}^{n+1} \dfrac{1}{i(i+1)} = \dfrac{n+1}{n+2}$

This completes the mathematical induction proof.

We can also verify this using SageMath that our guessed formula is
right:

#+begin_src sage :exports both
sum(f(i),i,1,n)
#+end_src

#+RESULTS:
: n/(n + 1)

*** Solution b

We need to verify that $\dfrac{1}{i+1} = \dfrac{1}{i} - \dfrac{1}{i+1}$

$\dfrac{1}{i} - \dfrac{1}{i+1}$

$= \dfrac{i+1-1}{i(i+1)}$

$= \dfrac{i}{i(i+1)}$

$= \dfrac{1}{i+1}$

Now let's use this fact to write part(a) as telescoping sum.

#+begin_src sage :exports both
i = var(i)
f1 = (1/i)
f2 =  - (1/(i+1))
[f1(1), f2(1), f1(2), f2(2), f1(3), f2(3), f1(n-1), f2(n-1), f1(n), f2(n)]
#+end_src

#+RESULTS:
: [1, -1/2, 1/2, -1/3, 1/3, -1/4, 1/(n - 1), -1/n, 1/n, -1/(n + 1)]

We can see how all the terms cancel out except the first one and the last term. So,

$\sum_{i=1}^{n} \dfrac{1}{i(i+1)} = 1 - \dfrac{1}{n+1}$

$= \dfrac{n}{n+1}$
