* Definite Integrals

** Solution 1

$\int_0^3 (2x+1) \mathrm{d}x$

Suppose $n$ is a positive integer. We begin by computing all of the
quantities mentioned in Definition 5.3.1. We have $f(x) = 2x + 1, a =
0, b = 3$, so $\Delta x = \dfrac{(b-a)}{n}$

$= \dfrac{3-0}{n} = \dfrac{3}{n}$

Next, the points that divided the interval $[0,3]$ into $n$ smaller
intervals are given by the formula

$x_i = a + i \Delta x = 0 + i \dfrac{3}{n} = \dfrac{3i}{n}$

Finally, we must choose the sample points $x^{*}_i \in [x_{i-1},
x_i]$. According to theorem 5.3.2, it doesn't matter what choice we
make; all choices will lead to the same value when we take the limit
of the Riemann $n$ sum as $n \to \infty$.

Let $x_i^{*} = x_i = \dfrac{3i}{n}$

We can now work out a formula for the Riemann sum:

$R_n = \sum_{i=1}^n f(x_i^{*})\Delta x = \sum_{i=1}^n f(\dfrac{3i}{n}) * \dfrac{3}{n}$

$= \sum_{i=1}^n ( \dfrac{6i}{n} + 1)* \dfrac{3}{n}$

Let's compute the result via SageMath:

#+begin_src sage :session nix
i,n = var('i n')
f = (6*i/n + 1) * (3/n)
soln = sum(f, i, 1, n)
soln.simplify_full()
#+end_src

#+RESULTS:
: 3*(4*n + 3)/n

#+begin_src sage :session nix
soln.expand()
#+end_src

#+RESULTS:
: 9/n + 12

Now we know that $R_n = \dfrac{9}{n} + 12$

$\int_0^3 (2x+1) \mathrm{d}x = \lim_{n \to \infty} R_n = \lim_{n \to \infty} \dfrac{9}{n} + 12 = 12$

** Solution 2

$\int_1^3 (2x+1) \mathrm{d}x$

Suppose $n$ is a positive integer. We begin by computing all of he
quantities mentioned in Definition 5.3.1. We have $f(x) = 2x + 1, a =
1, b = 3$, so $\Delta x = \dfrac{(b-a)}{n}$

$= \dfrac{3-1}{n} = \dfrac{2}{n}$

Next, the points that divided the interval $[1,3]$ into $n$ smaller
intervals are given by the formula

$x_i = a + i \Delta x = 1 + i \dfrac{2}{n} = 1 + \dfrac{2i}{n}$

Finally, we must choose the sample points $x^{*}_i \in [x_{i-1},
x_i]$. According to theorem 5.3.2, it doesn't matter what choice we
make; all choices will lead to the same value when we take the limit
of the Riemann $n-$ sum as $n \to \infty$.

Let $x_i^{*} = x_i = 1 + \dfrac{2i}{n}$

We can now work out a formula for the Riemann sum:

$R_n = \sum_{i=1}^n f(x_i^{*})\Delta x = \sum_{i=1}^n f(1 + \dfrac{2i}{n}) * \dfrac{2}{n}$

$= \sum_{i=1}^n ( 2 + \dfrac{4i}{n} + 1)* \dfrac{2}{n}$

Let's compute the result via SageMath:

#+begin_src sage :session nix
i,n = var('i n')
f = (2 + (4*i/n) + 1) * (2/n)
soln = sum(f, i, 1, n)
soln.expand()
#+end_src

#+RESULTS:
: 4/n + 10

Now we know that $R_n = \dfrac{4}{n} + 10$

$\int_0^3 (2x+1) \mathrm{d}x = \lim_{n \to \infty} R_n = \lim_{n \to \infty} \dfrac{4}{n} + 10 = 10$

We can also verify the above result using sagemath:

#+begin_src sage :session nix
integrate(2*x + 1, x, 1, 3)
#+end_src

#+RESULTS:
: 10

** Solution 3

$\int_0^4 x^2 \mathrm{d}x$

Suppose $n$ is a positive integer. We begin by computing all of the
quantities mentioned in Definition 5.3.1. We have $f(x) = x^2, a =
0, b = 4$, so $\Delta x = \dfrac{(b-a)}{n}$

$= \dfrac{4-0}{n} = \dfrac{4}{n}$

Next, the points that divided the interval $[0,4]$ into $n$ smaller
intervals are given by the formula

$x_i = a + i \Delta x = 0 + i \dfrac{4}{n} = \dfrac{4i}{n}$

Finally, we must choose the sample points $x^{*}_i \in [x_{i-1},
x_i]$. According to theorem 5.3.2, it doesn't matter what choice we
make; all choices will lead to the same value when we take the limit
of the Riemann $n$ sum as $n \to \infty$.

Let $x_i^{*} = x_i = \dfrac{4i}{n}$

We can now work out a formula for the Riemann sum:

$R_n = \sum_{i=1}^n f(x_i^{*})\Delta x = \sum_{i=1}^n f(\dfrac{4i}{n}) * \dfrac{4}{n}$

$= \sum_{i=1}^n ( \dfrac{16i^2}{n^2})* \dfrac{4}{n}$

Let's compute the result via SageMath:

#+begin_src sage :session nix
i,n = var('i n')
f = (16 * i^2 / n^2) * (4/n)
soln = sum(f, i, 1, n)
soln.expand()
#+end_src

#+RESULTS:
: 32/n + 32/3/n^2 + 64/3

So, $R_n = 32/n + 32/3/n^2 + 64/3$

$\int_0^4 x^2 \mathrm{d}x = \lim_{n \to \infty} R_n = \dfrac{64}{3}$

** Solution 4

$\int_1^3 (4-x^2) \mathrm{d}x$

Suppose $n$ is a positive integer. We begin by computing all of the
quantities mentioned in Definition 5.3.1. We have $f(x) = 4 - x^2, a =
1, b = 3$, so $\Delta x = \dfrac{(b-a)}{n}$

$= \dfrac{3-1}{n} = \dfrac{2}{n}$

Next, the points that divided the interval $[1,3]$ into $n$ smaller
intervals are given by the formula

$x_i = a + i \Delta x = 1 + i \dfrac{2}{n} = 1 + \dfrac{2i}{n}$

Finally, we must choose the sample points $x^{*}_i \in [x_{i-1},
x_i]$. According to theorem 5.3.2, it doesn't matter what choice we
make; all choices will lead to the same value when we take the limit
of the Riemann $n$ sum as $n \to \infty$.

Let $x_i^{*} = x_i = 1 + \dfrac{2i}{n}$

We can now work out a formula for the Riemann sum:

$R_n = \sum_{i=1}^n f(x_i^{*})\Delta x = \sum_{i=1}^n f(1 + \dfrac{2i}{n}) * \dfrac{2}{n}$

$= \sum_{i=1}^n ( 4 - (1 + \dfrac{2i}{n})^2)* \dfrac{2}{n}$

Let's compute the result via SageMath:

#+begin_src sage :session nix
i,n = var('i n')
f = (4 - (1 + (2*i/n))^2) * (2/n)
soln = sum(f, i, 1, n)
soln.expand()
#+end_src

#+RESULTS:
: -8/n - 4/3/n^2 - 2/3

So, $R_n = -8/n - 4/3/n^2 - 2/3$

$\int_1^3 (4-x^2) \mathrm{d}x = \lim_{n \to \infty} R_n = \dfrac{-2}{3}$

We can also verify the above result using sagemath:

#+begin_src sage :session nix
integrate(4-x^2, x, 1, 3)
#+end_src

#+RESULTS:
: -2/3
